### PR TITLE
cgroups/cgfsng: fixes, features, and improved cgroup2 handling

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
Fwiw, the failure is unrelated to any interesting changes. The current failure is caused by the new logging functions I implemented for the constructor. They print to stderr so when `liblxc` `exec()`s `lxc-user-nic` and then reads back from `std{out,err}` to capture the output that is sent to it it'll read back the contents of the log as well which is why `lxc-user-nic` fails which is is why the container fails to start. This only affects unprivileged containers started by unprivileged users they are the only containers that need to use `lxc-user-nic`. Note, the two tests that fail need to run as root but they drop to an unprivileged users before they do anything interesting with containers.

**Comment by brauner** [comment]
Note that for unprivileged containers that - for whatever strange reason - still drop `CAP_SYS_ADMIN` in their own user namespace we only ever mount hierarchies that are writable by she container. I think this is more secure and correct behavior because it means that any hierarchy in which the container is not placed into its own writable cgroup will not be visible to it and the container also won't be able to mount it by itself. This prevents quite some information leaks.

**Comment by brauner** [comment]
jenkins: test this please

**Comment by hallyn** [comment]
Looks good, though the last patch seems misplaced.

**Pull request merged**
