### PR TITLE
fix issue 2765

### PR DESCRIPTION
**Pull request by avkvl**
Hi,
I think this will solve issue #2765.
Please, take a look.
Thanks

### CODE REVIEW

**Comment by brauner** [comment]
Hey, thanks for the patch. Can you please sign-off your commit. :)

**Comment by avkvl** [comment]
> Hey, thanks for the patch. Can you please sign-off your commit. :)

Done.
This is my first pull request on github.

Can you please backport fix to stable-2.0 branch and make new tag 2.0.x (we are using Ubuntu 16.04)?
Thanks

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Thanks!

**Pull request merged**
