### PR TITLE
lxc_usernsexec: continuing after unshare fails leads to confusing and…

### PR DESCRIPTION
**Pull request by xmcqueen**
… misleading error messages

### CODE REVIEW

**Comment by brauner** [comment]
Can you please sign-off your commit? :)

**Comment by xmcqueen** [comment]
I think I signed it with a key that has the wrong email address.  I'll have to fix that.  Its showing "unverified" on the commits page.  Is there a simple fix for this?  I think not and I'll have to redo it.  I'll get back to this.

**Comment by xmcqueen** [comment]
i think I fixed the key

**Comment by xmcqueen** [comment]
nope. will resubmit the pr

**Pull request closed without merging**
