### PR TITLE
python-lxc: fix breakage caused by the switch to setuptools

### PR DESCRIPTION
**Pull request by amezin**
Looks like it's a bug in Debian or Ubuntu Python/setuptools patches.
When `--install-layout=deb` is passed to `setup.py`, setuptools don't generate stub helpers for loading extensions from .egg files. The same command without `--install-layout` works as expected.

However, it could simply be an unsupported configuration, because distro packages should be built with `--single-version-externally-managed`, which prevents .egg builds.

So, I assume setuptools builds will be used for distro packages. Then the fix is very simple: always pass `--root=` to `setup.py`, even when `DESTDIR` isn't set. As `--root` implies `--single-version-externally-managed`.

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Hi @amezin, unfortunately it's still failing:

```
FAIL: python3: API
---
Traceback (most recent call last):
  File "/tmp/tmp.016U6HBGQr", line 26, in <module>
    import lxc
  File "/usr/lib/python3/dist-packages/lxc-0.1-py3.4-linux-x86_64.egg/lxc/__init__.py", line 26, in <module>
ImportError: No module named '_lxc'
---
```

**Comment by amezin** [comment]
@brauner 

    if [ -z "" ]; then \
    		cd . && /usr/bin/python3 setup.py build -b /build/src/python-lxc/build install --prefix=/usr --no-compile --install-layout=deb; \
    	else \
    		cd . && /usr/bin/python3 setup.py build -b /build/src/python-lxc/build install --prefix=/usr --no-compile --install-layout=deb --root=; \
    	fi

These lines don't exist anymore in Makefile.am (removed in https://github.com/lxc/lxc/pull/1036/commits/371cffc37af4e7af67bad4430d8535c09410a748), but I see them in Jenkins output

**Comment by brauner** [comment]
Yeah, I see it too.

**Comment by brauner** [comment]
But that's expected, isn't it because of:

```
INSTALL_OPTS := install --prefix=$(prefix) --no-compile $(DISTSETUPOPTS)
CALL_SETUP_PY := cd @srcdir@ && $(PYTHON) setup.py build -b @abs_builddir@/build
```
in `Makefile.am`.

**Comment by brauner** [comment]
Ah, I see. Your new commit removed those lines.

**Comment by amezin** [comment]
@brauner I've removed INSTALL_OPTS in this PR too. https://github.com/lxc/lxc/pull/1036/files

Looks like Jenkins tests master branch instead of the PR.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
There indeed is something wrong with Jenkins... looking into it now.

jenkins: test this please

**Comment by stgraber** [comment]
We are being hit by https://github.com/jenkinsci/ghprb-plugin/issues/355

**Comment by ar45** [comment]
@stgraber yes, I also spent hours figuring that last night.

**Comment by stgraber** [comment]
Merging this. The code change seems reasonable and we'll have Jenkins check it when it hits master.

**Pull request merged**
