### PR TITLE
Fixes after coverity scan

### PR DESCRIPTION
**Pull request by mihalicyn**

### CODE REVIEW

**Comment by mihalicyn** [comment]
Test failures only on arm64:

```
FAIL: lxc-tests: lxc-test-autostart (153s)
---
lxc-wait: lxc-test-auto: ../src/lxc/commands_utils.c: lxc_cmd_sock_rcv_state: 49 Resource temporarily unavailable - Failed to receive message
lxc-wait: lxc-test-auto: ../src/lxc/state.c: lxc_wait: 103 Resource temporarily unavailable - Failed to receive state from monitor
Container didn't stop
FAIL
```


```
+ /build/lxc-exercise
FAIL: lxc-tests: lxc-test-api-reboot (856s)
---
reboot: lxc-api-reboot: ../src/lxc/commands_utils.c: lxc_cmd_sock_rcv_state: 49 Resource temporarily unavailable - Failed to receive message
../src/tests/api_reboot.c: 119: main: Failed to reboot container "reboot"
```

Does it look like we need to increase timeouts for the arm64 tests?

**Review by brauner — APPROVED** [review]

**Comment by brauner** [comment]
> Test failures only on arm64:
> 
> ```
> FAIL: lxc-tests: lxc-test-autostart (153s)
> ---
> lxc-wait: lxc-test-auto: ../src/lxc/commands_utils.c: lxc_cmd_sock_rcv_state: 49 Resource temporarily unavailable - Failed to receive message
> lxc-wait: lxc-test-auto: ../src/lxc/state.c: lxc_wait: 103 Resource temporarily unavailable - Failed to receive state from monitor
> Container didn't stop
> FAIL
> ```
> 
> ```
> + /build/lxc-exercise
> FAIL: lxc-tests: lxc-test-api-reboot (856s)
> ---
> reboot: lxc-api-reboot: ../src/lxc/commands_utils.c: lxc_cmd_sock_rcv_state: 49 Resource temporarily unavailable - Failed to receive message
> ../src/tests/api_reboot.c: 119: main: Failed to reboot container "reboot"
> ```
> 
> Does it look like we need to increase timeouts for the arm64 tests?

Yeah, we could at least try but it's a weird error.

**Comment by mihalicyn** [comment]
https://github.com/lxc/lxc/commit/b7aa56b85ca96f321ef6aadb60a28f8c16bec44d

I'm thinking about increasing this sleep's time.

**Comment by mihalicyn** [comment]
Another failure:
```
[vm] $ /bin/sh -xe /tmp/jenkins5022350431304334345.sh
+ cd /lxc-ci
+ exec sudo /lxc-ci/bin/testbuild-clang arm64 https://github.com/lxc/lxc master 62634e93b0de9e177205241d539505c31e868e45
Device loop-control added to lxc-test-c173120f-f5ab-4ac1-83da-af2867724645
Error: Failed to get profiles: Failed to begin transaction: context deadline exceeded
Build step 'Execute shell' marked build as failure
```

**Comment by mihalicyn** [comment]
https://github.com/lxc/lxc/issues/4237 appeared again in Sanitizers build / sanitizers (clang) (

**Comment by mihalicyn** [comment]
Unfortunately, increasing the interval to 10s is not effective on ARM64:
```
FAIL: lxc-tests: lxc-test-autostart (169s)
---
lxc-wait: lxc-test-auto: ../src/lxc/commands_utils.c: lxc_cmd_sock_rcv_state: 49 Resource temporarily unavailable - Failed to receive message
lxc-wait: lxc-test-auto: ../src/lxc/state.c: lxc_wait: 103 Resource temporarily unavailable - Failed to receive state from monitor
Container didn't stop
FAIL
```

**Pull request merged**
