### PR TITLE
Start error message fix1

### PR DESCRIPTION
**Pull request by krichter722**
added hint about option to use for foreground mode in start error message and introduced necessary string literal reusage (not too elegant for instance, but no need to change for all literals as long as there's no reusage - I can do it if you think it's valuable (open an issue and reference or assign me)).

### CODE REVIEW

**Comment by stgraber** [comment]
Hi,

Your last commit is missing the Signed-off-by line.

**Comment by stgraber** [comment]
Also the switch to constants is making things much harder to read and almost impossible for somebody to grep, so I'd prefer we don't do that.

Would you mind updating your branch to only updating the error message and dropping those constants?

Thanks!

**Comment by krichter722** [comment]
Do you really want to maintain string literals in two places? I offer to convert everything to constants in order to increase readability by systematic.

**Comment by stgraber** [comment]
Yes, I'd much rather have to update strings in two places if we ever change them (and we won't as that'd break every existing script out there) than break the ability of people to grep for strings in our code.

**Comment by krichter722** [comment]
The constants are still grepable.

**Comment by stgraber** [comment]
No they're not.
Before your change I could grep for "-F, --foreground", after it, I can't and I have to more cleverly grep for part of the string I see on my screen.

**Comment by krichter722** [comment]
I added this as a comment. The code maintainability shouldn't suffer from such a rare (if not strange) use case for developers.

**Comment by stgraber** [comment]
Apparently I wasn't clear enough...

I'm not going to merge this branch until those constants are gone.
That code change makes the code uglier, requires thinking to replace those constants with their value in your head and that for no gain as we're not going to change those arguments and even if we were, we'd still be grepping through the whole project to make sure we haven't missed anything.

**Comment by krichter722** [comment]
> requires thinking to replace those constants with their value in your head
No. If you use constants correctly/consequently, you don't - that's the purpose of constants.

> we'd still be grepping through the whole project to make sure we haven't missed anything.
That sounds like a very inefficient, unreliable way of developing.

> I'm not going to merge this branch until those constants are gone.
I strongly recommend to get rid of the mentioned development techniques. Then we'll talk again. On the long term I could contribute such changes, but only after you're convinced they're an improvement. github.com offers gitter chat. We can move this conversation there if you want.

**Pull request closed without merging**
