### PR TITLE
conf: Fixes uninitialised variable.

### PR DESCRIPTION
**Pull request by tomponline**
Signed-off-by: tomponline <tomp@tomp.uk>

### CODE REVIEW

**Comment by tomponline** [comment]
@brauner clang is failing but gcc passes, would it be OK to initialise this to 0?

**Comment by brauner** [comment]
Ah, f*ck, I accidently merged.

**Comment by brauner** [comment]
Fixing this in:
https://github.com/lxc/lxc/pull/2896

**Comment by tomponline** [comment]
> Fixing this in:
> #2896

Thanks that makes more sense. :)

**Pull request merged**
