### PR TITLE
conf: only use newuidmap and newgidmap when necessary

### PR DESCRIPTION
**Pull request by 3XX0**
Signed-off-by: Jonathan Calmels <jcalmels@nvidia.com>

This is useful for users that are not in `/etc/sub{u,g}id` and only want to remap themselves like so:
```
lxc.idmap = u 1000 1000 1                                                                                                                                                                                           
lxc.idmap = g 1000 1000 1
lxc.init.uid = 1000
lxc.init.gid = 1000
```

Without this the container fails to launch and the cgroups aren't torn down properly for some reason. When retrying you will get:
```
lxc-execute cuda 20180609002300.889 ERROR    lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1246 - The cgroup "/sys/fs/cgroup/systemd/user.slice/user-1000.slice/session-121.scope/lxc/cuda" already existed
lxc-execute: cuda: cgroups/cgfsng.c: create_path_for_hierarchy: 1246 The cgroup "/sys/fs/cgroup/systemd/user.slice/user-1000.slice/session-121.scope/lxc/cuda" already existed
```
@brauner hopefully it's easy to fix ^

With this patch the container will start properly, with harmless error messages:
```
lxc-execute cuda 20180609002300.954 ERROR    lxc_utils - utils.c:lxc_setgroups:2074 - Operation not permitted - Failed to setgroups().
lxc-execute: cuda: utils.c: lxc_setgroups: 2074 Operation not permitted - Failed to setgroups().
lxc-init cuda 20180609002301.179 ERROR    lxc_init - cmd/lxc_init.c:remove_self:211 - Operation not permitted - Failed to unmount "/usr/local/sbin/init.lxc.static"
```
Not sure how to solve/silent these, since `setgroups` is prevented by `/proc/self/setgroups` and `umount` by `CAP_SYS_ADMIN` being dropped on exec.

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Thanks! :)

**Pull request merged**
