### PR TITLE
lxc-user-nic: improvements

### PR DESCRIPTION
**Pull request by brauner**

### CODE REVIEW

**Comment by brauner** [comment]
@stgraber, also adds the code to cleanup the link when the rename fails.

**Comment by stgraber** [comment]
Looks good to me, though given this is a setuid tool, I'd feel better if @hallyn could review it too.

**Comment by hallyn** [comment]
In the future, I'd really really appreciate if any patch which has a long sequence of "should have zero functionality changes" not be mixed with functional changes.

Note also that alloca() per the manpage does not return NULL on error - just gives SEGV on access :)  There may be some libc where that's not the case though so let's leave your fix as is.

**Comment by hallyn** [comment]
(yeah, thanks stgraber, I'd actually downloaded the patch yesterday morning but have been largely sans laptop since)

**Comment by hallyn** [comment]
In patch 2 can you please --amend with a description of the bugfix?

**Comment by brauner** [comment]
Hm, actually the only patch that changes functionality should be the third one. I intended to keep them separate. Are there functionality changes in the others?

**Comment by hallyn** [comment]
Oh, I was going by the commit message.  I hadn't yet seen a functional change which was why i was asking :)

**Comment by brauner** [comment]
@hallyn, yeah, the mention of "bugfix" in the second commit referred to a couple of unchecked `strdup()`s. :)

**Comment by brauner** [comment]
Which I didn't consider functional changes in any relevant sense. :)

**Pull request merged**
