### PR TITLE
bugfixes

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>
Signed-off-by: Adrian Reber <areber@redhat.com>

### CODE REVIEW

**Comment by hallyn** [comment]
patch 2 *looks* fine to me.  Test suite fails though :)

**Comment by brauner** [comment]
@hallyn, yeah, I'm on it. We changed how `<storage-type>:<container-path>` is parsed. This needs more changes then I anticipated but is cleaner in the long run. :)

**Comment by stgraber** [comment]
@hallyn can you take a look at this one?

**Comment by brauner** [comment]
jenkins: test this please

**Pull request merged**
