### PR TITLE
Rcfile as common arg

### PR DESCRIPTION
**Pull request by Blub**
I put the `c->configfile` change into a separate commit - I'm unsure whether it would be a better idea to add a call for that or even let `c->load_config()` handle this, but that could be a potentially breaking change for some library users, so for now I went with just setting it directly.

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by Blub** [comment]
Changes in the update:
* only includes `--rcfile` now, not `-f` as it otherwise conflicts with `lxc-destroy`'s force option
* added forgotten config load code to `lxc-copy` (previously only contained the usage change)

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by Blub** [comment]
Changes in the update:
  undid the accidental removal of the `-f` option in `lxc-attach`

**Comment by brauner** [comment]
jenkins: test this please

**Pull request merged**
