### PR TITLE
Add Verbose Output in Download Template

### PR DESCRIPTION
**Pull request by petermichaux**
I have been studying the anatomy of an LXC image server. I haven't been able to find a written description of an LXC image server so I have been reverse engineering by reading the LXC download template. It was helpful to see the URLs of the files that the LXC download template was downloading.

### CODE REVIEW

**Comment by petermichaux** [comment]
I don't know why github added the second commit fixing error message to this pull request.

**Comment by stgraber** [comment]
Missing `Signed-off-by` line in both commits.

**Comment by petermichaux** [comment]
I have no idea how to fix that. What do I do?

**Comment by stgraber** [comment]
With multiple commits, you should be able to do it with something like `git rebase HEAD^^ --signoff` followed by `git push --force`.

Note that this assumes that your git configuration has a user name and email configured, for example:
```
[user]
	name = Stéphane Graber
	email = stgraber@stgraber.org
```

**Comment by petermichaux** [comment]
@stgraber Is everything ok with these commits now?

**Review by stgraber — APPROVED** [review]

**Comment by stgraber** [comment]
Yep, all good, thanks!

**Pull request merged**
