### PR TITLE
caps: skip file capability checks on android

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
@stgraber, @hallyn, should be good to merge.

**Comment by hallyn** [comment]
This really seems the wrong way to go about it.  @brauner can I interest you in autoconf'ing it, or would you prefer I do it?

**Comment by brauner** [comment]
@hallyn, yeah, as I've said on IRC I think `configure.ac` seems better than to special-case bionic. I'll send a patch. :)

**Comment by hallyn** [comment]
Oh sorry, I completely missed where you said that on IRC.  Thanks.

**Comment by brauner** [comment]
@hallyn, np at all. :)

**Pull request merged**
