### PR TITLE
2016 03 16/cgroupauto

### PR DESCRIPTION
**Pull request by hallyn**
Not sure about the second patch.  Do we want cgmanager to be used if available and compiled in, or not?

### CODE REVIEW

**Comment by brauner** [comment]
What behavior do we expect for systems that do not handout writeable cgroups for crucial subsystems on login? If having cgmanager available will make it easier to deal with the aforementioned case than we should keep it in. If not let's definitely kick it; smaller codebase => easier maintenance. :)

**Comment by stgraber** [comment]
@hallyn gcc looks unhappy

**Comment by stgraber** [comment]
I think we need to keep cgmanager around for a bit just for backport's and so long as we keep the code around, I think it makes sense to use it over cgfsng when it's available and LXC was built with it.

**Comment by brauner** [comment]
The `c99` trap with `gcc`; `clang` always allows for-loop initial declarations, `gcc` doesn't.

**Pull request merged**
