### PR TITLE
Fixed logic in memory controller check to support linux >3.x

### PR DESCRIPTION
**Pull request by diego-XA**
This fixes https://github.com/lxc/lxc/issues/508

### CODE REVIEW

**Comment by stgraber** [comment]
Your commit message is missing the required Signed-off-by line

**Comment by diego-XA** [comment]
Thanks for reporting it and sorry for the mistake. It should be fixed now.

**Comment by stgraber** [comment]
Hi,

Thanks for fixing the commit message.

Looks like your branch now needs rebasing, possibly because of another lxc-checkconfig fix which just got merged.

**Comment by s7v7nislands** [comment]
ping

**Comment by diego-XA** [comment]
Sorry for the delay on this. You can disregard this pull request as the bug it fixed was fixed by a previous PR.

**Comment by stgraber** [comment]
Ok, thanks!

**Comment by alkino** [comment]
Fixed by #498

**Pull request closed without merging**
