### PR TITLE
simple enhancements of lxc-debian-template-script

### PR DESCRIPTION
**Pull request by LicoMonch**
Nothing special in these commits (imho). Just a few changes explained by the commit-messages.

### CODE REVIEW

**Comment by brauner** [comment]
Could you please prefix your commits with "templates:" e.g. "templates: avoid noisy perl warnings caused by missing locales" etc. These are a lot of small changes. Did you test that the template still works?

**Comment by LicoMonch** [comment]
The commit messages were changed as requested.

The template still works (tested with 2.0.3-0ubuntu1~ubuntu16.04.1) in any combination of parameters set.
The greatest danger is the quoting of variables here and I focused on path-names and some minor other vars.
I also checked that variables like "$packages" are passed without quotes if needed (eg ```apt-get install "$packages"``` would not work,, so I didn't modify that)

**Comment by brauner** [comment]
jenkins: test this please

**Comment by LicoMonch** [comment]
I'm not familiar with jenkins, but to me the failed lxc-test-usernic relates to ubuntu-containers and not to debian.

Locally this test also passes here (lxc-tests 2.0.3-0ubuntu1~ubuntu16.04.1)

**Pull request merged**
