### PR TITLE
cgroups: remove unused method and cleanup cgroup_exit()

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
What's going on with i386?

**Comment by brauner** [comment]
> What's going on with i386?

I've been mentioning this a couple of times on Telegram and on IRC and was asking whether there's anything that we did to the builders. We haven't had a clean build on there for a long time.

**Comment by stgraber** [comment]
Nope, must be something in the testsuite, they behave fine for lxd

**Comment by stgraber** [comment]
Test rubbing i386 kernel the wrong way or running us out of memory?

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
