### PR TITLE
API: add console ringbuffer extension

### LINKED ISSUE #1870: API: add console ringbuffer API extensions
Since we merged the console ringbuffer implementation we now need at least two new API calls. For example:

- `console_get_ringbuffer()`
- `console_clear_ringbuffer()`

Or maybe just one `console_ringbuffer()`?

### PR DESCRIPTION
**Pull request by brauner**
Closes #1870.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
I think we call the API function `console_log()` and give it a `struct console_log` as second argument. I'll push an RFC on top of this patchset soon.

**Comment by brauner** [comment]
Ok, so I've changed the API extension quite a lot in a commit I pushed on top of this patchset. Please don't merge this yet until I a) removed the `lxc-console` patches and b) I squashed the commits once we all agree that the layout for the new API extension is fine. Here's the TL;DR:

- new function is:
`int (*console_log)(struct lxc_container *c, struct console_log *log)`
- new struct is added
```
struct console_log {
	/* Clear the console log. */
	bool clear;

	/* Retrieve the console log. */
	bool read;

	/* This specifies the maximum size to read from the ringbuffer. Setting
	 * it to 0 means that the a read can be as big as the whole ringbuffer.
	 * On return callers can check how many bytes were actually read.
	 * If "read" and "clear" are set to false and a non-zero value is
	 * specified then up to "read_max" bytes of data will be discarded from
	 * the ringbuffer.
	 */
	uint64_t *read_max;

	/* Data that was read from the ringbuffer. If "read_max" is 0 on return
	 * "data" will be NULL.
	 */
	char *data;
};
```

I think the struct makes sense since it will allows us to easily expand or deprecate operations on the ringbuffer.
Having the ringbuffer contents be returned in the struct enables us to return meaningful errors via the return value of `console_log()`. For example, callers can check for `-ENODATA` which I find quite useful. It also allows the API to do sensible logging outside of the actual command infrastructure. I prefer this very much since it keeps it apap (as performant as possible :)).

**Comment by brauner** [comment]
See here for an illustration:

[asciicast](https://asciinema.org/a/143528)

**Comment by hallyn** [comment]
(Hi - I'm assuming this has been on hold for Prague (given the last commit title) - please ping me when ready)

**Comment by brauner** [comment]
@hallyn, actually it is ready for review. :)

**Comment by stgraber** [comment]
@hallyn

**Comment by hallyn** [comment]
Present.

(looking)

**Comment by hallyn** [comment]
One thing about this API is that - if I don't miss something - it is easy to have a situation where

buffer has 200 bytes
user asks to read 100 bytes and clear the buffer
second 100 bytes are lost.

I'm probably misreading.

**Comment by brauner** [comment]
If the user sets `clear = true` the ringbuffer gets wiped completely even if the user just requests to read 100 bytes. If the user only wants to discard 100 bytes after the read then `clear` should simply be left unset. What would you prefer?

**Comment by hallyn** [comment]
Sorry, I'm not thinking about this quite right.  I need to look through and understand what happens with multiple concurrent readers.  Will comment after I grok that again.

**Comment by hallyn** [comment]
...  so is there any point to ever calling ringbuf_clear()?  since doing a read advances the read pointer.

**Comment by brauner** [comment]
If you want to clear the complete buffer without reading from it.

**Comment by hallyn** [comment]
Ok.  I'm good with it - thanks.

**Pull request merged**
