### PR TITLE
tree-wide: bugfixes

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
@2xsec, I think I'll go with:
```
---
 src/include/netns_ifaddrs.c | 45 ++++++++++++++++---------------------
 1 file changed, 19 insertions(+), 26 deletions(-)

diff --git a/src/include/netns_ifaddrs.c b/src/include/netns_ifaddrs.c
index fc0ffc16..fad1c628 100644
--- a/src/include/netns_ifaddrs.c
+++ b/src/include/netns_ifaddrs.c
@@ -393,45 +393,38 @@ static int __ifaddrs_netlink_recv(int fd, unsigned int seq, int type, int af,
 	} u;
 	int r, property, ret;
 
-	if (type == RTM_GETLINK)
-		buf = getlink_buf;
-	else if (type == RTM_GETADDR)
-		buf = getaddr_buf;
-	else
-		return -1;
-
-	memset(buf, 0, sizeof(*buf));
-
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wcast-align"
 	hdr = (struct nlmsghdr *)buf;
-	if (type == RTM_GETLINK)
+	if (type == RTM_GETLINK) {
 		ifi_msg = (struct ifinfomsg *)__NLMSG_DATA(hdr);
-	else
-		ifa_msg = (struct ifaddrmsg *)__NLMSG_DATA(hdr);
+		ifi_msg->ifi_family = af;
 
-	if (type == RTM_GETLINK)
 		hdr->nlmsg_len = NLMSG_LENGTH(sizeof(*ifi_msg));
-	else
+
+		buf = getlink_buf;
+
+		property = IFLA_TARGET_NETNSID;
+	} else if (type == RTM_GETADDR) {
+		ifa_msg = (struct ifaddrmsg *)__NLMSG_DATA(hdr);
+		ifa_msg->ifa_family = af;
+
 		hdr->nlmsg_len = NLMSG_LENGTH(sizeof(*ifa_msg));
+
+		buf = getaddr_buf;
+
+		property = IFA_TARGET_NETNSID;
+	} else {
+		errno = EINVAL;
+		return -1;
+	}
+	memset(buf, 0, sizeof(*buf));
 #pragma GCC diagnostic pop
 
 	hdr->nlmsg_type = type;
 	hdr->nlmsg_flags = NLM_F_DUMP | NLM_F_REQUEST;
 	hdr->nlmsg_pid = 0;
 	hdr->nlmsg_seq = seq;
-	if (type == RTM_GETLINK)
-		ifi_msg->ifi_family = af;
-	else
-		ifa_msg->ifa_family = af;
-
-	errno = EINVAL;
-	if (type == RTM_GETLINK)
-		property = IFLA_TARGET_NETNSID;
-	else if (type == RTM_GETADDR)
-		property = IFA_TARGET_NETNSID;
-	else
-		return -1;
 
 	if (netns_id >= 0)
 		addattr(hdr, 1024, property, &netns_id, sizeof(netns_id));
-- 
2.19.1

```

**Comment by hallyn** [comment]
I'm a bit worried about ' [PATCH 14/19] cmd/lxc_init: remove tautological check' - you remove a setting of ret to EXIT_SUCCESS.  So if you fail to send SIGALARM to all children, for instance, you may end up exiting -1 where before you would have exited with EXIT_SUCCESS.

**Comment by hallyn** [comment]
I'm a bit worried about ' [PATCH 14/19] cmd/lxc_init: remove tautological check' - you remove a setting of ret to EXIT_SUCCESS.  So if you fail to send SIGALARM to all children, for instance, you may end up exiting -1 where before you would have exited with EXIT_SUCCESS.

**Comment by hallyn** [comment]
I'm a bit worried about ' [PATCH 14/19] cmd/lxc_init: remove tautological check' - you remove a setting of ret to EXIT_SUCCESS.  So if you fail to send SIGALARM to all children, for instance, you may end up exiting -1 where before you would have exited with EXIT_SUCCESS.

**Comment by hallyn** [comment]
I'm a bit worried about ' [PATCH 14/19] cmd/lxc_init: remove tautological check' - you remove a setting of ret to EXIT_SUCCESS.  So if you fail to send SIGALARM to all children, for instance, you may end up exiting -1 where before you would have exited with EXIT_SUCCESS.

**Comment by hallyn** [comment]
I'm a bit worried about ' [PATCH 14/19] cmd/lxc_init: remove tautological check' - you remove a setting of ret to EXIT_SUCCESS.  So if you fail to send SIGALARM to all children, for instance, you may end up exiting -1 where before you would have exited with EXIT_SUCCESS.

**Comment by brauner** [comment]
Yeah, I'll drop that one, @hallyn.

**Pull request merged**
