### PR TITLE
cgfsng: use `\r\n` instead of `\n` in cgfsng debug code

### PR DESCRIPTION
**Pull request by 0x0916**
Fix: https://github.com/lxc/lxc/issues/1697

Signed-off-by: Long Wang <w@laoqinren.net>

### CODE REVIEW

**Comment by hallyn** [comment]
Why?

**Comment by 0x0916** [comment]
@hallyn During the container start, after call `lxc_set_tios` which change console's terminal settings. 

`\n` will only print on the new line and not at the start of the line.

**Comment by hallyn** [comment]
I don't see that function anywhere - lxc_set_tios

@brauner, I'll leave this to you - I prefer not to splatter \n's about if
we can help it, but if it's needed then it's needed.

IMO in general it's better to encourage users to redirect log to a file
than ever try to read it on a console, especially if non-backgrounded
container.

**Comment by 0x0916** [comment]
@hallyn sorry, the function name is `lxc_setup_tios`.

**Comment by brauner** [comment]
Yeah, I'm not sure that this is actually worth it given that we'd introduce some parsing weirdness if we pring `\r\n`. If this doesn't p*ss you off too much @0x0916 I'd close this (or you do). :)

**Pull request closed without merging**
