### PR TITLE
fix thread-safe issue (localtime => localtime_r)

### PR DESCRIPTION
**Pull request by 2xsec**
Hello,

thread-safe issue is fixed.

Thanks.

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Thanks!

**Comment by 2xsec** [comment]
@brauner coverity issues are not fixed yet? I fixed some issues last week.

**Comment by brauner** [comment]
Coverity is sometimes strange in this regard. It currently doesn't seem to trigger a build but also doesn't report an error why it doesn't do it. The last check it did was a build that  I submitted manually.

**Comment by 2xsec** [comment]
@brauner ok! Thanks :)

**Comment by brauner** [comment]
I've manually submitted a build now. :)

**Pull request merged**
