### PR TITLE
conf: do not run the "mount" hooks twice

### PR DESCRIPTION
**Pull request by flx42**
Regression introduced by 8353b4c90ed18e570521134f2c60bef56a082b55

Signed-off-by: Felix Abecassis <fabecassis@nvidia.com>

### CODE REVIEW

**Comment by brauner** [comment]
@flx42, excellent catch! Thanks!

**Comment by brauner** [comment]
jenkins: test this please

**Comment by flx42** [comment]
Luckily `nvidia-container-cli` crashed and burned when called twice on the same rootfs.
I guess this can also happen if you declare our hook twice in the config, is this a case hooks should try to guard against?

**Comment by brauner** [comment]
@flx42, yeah, if you declare the same hook twice it get's run twice but there's nothing that LXC would be able to handle because it cannot easily tell if users do this intentionally or not.

**Pull request merged**
