### PR TITLE
lxc-usernsexec: lxc-usernsexec: introduce and use userns_exec() and implement -b, -u, and -g arguments

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by smoser** [comment]
So, using the 'test-usernsexec' version 
83bc20df57d26a35cd97c593baaf55cfb2825755 of
https://gist.github.com/smoser/d3dbf2b8a073675e0700472e12513e0a

I ran the following on focal with a build of your branch (c108dc7e).

I really would expect all of these to pass.  And they fail with no output.

Ie:

    $ lxc-usernsexec -- /bin/true ; echo $?
    255

Full output of the test-usernsexec

    $ DEBUG=2 ~/src/usernsexec/test-usernsexec 
    uid=1000 gid=1000 name=smoser subuid=100000 subgid=100000 ver=1:4.0.0-198-gc108dc7e-0upstream1
    lxc-utils=1:4.0.0-198-gc108dc7e-0upstream1 kver=5.4.0-29-generic
    USERNSEXEC=lxc-usernsexec TEST_CMD=/bin/true
    ----
    default  FAIL [255] lxc-usernsexec -- /bin/true
    UG..     PASS [0] lxc-usernsexec -mu:0:1000:1 -mg:0:1000:1 -- /bin/true
    UGu.     PASS [0] lxc-usernsexec -mu:0:1000:1 -mg:0:1000:1 -mu:1:100000:1 -- /bin/true
    UG.g     FAIL [255] lxc-usernsexec -mu:0:1000:1 -mg:0:1000:1 -mg:1:100000:1 -- /bin/true
    UGug     FAIL [255] lxc-usernsexec -mu:0:1000:1 -mg:0:1000:1 -mu:1:100000:1 -mg:1:100000:1 -- /bin/true
    B...     PASS [0] lxc-usernsexec -mb:0:1000:1 -- /bin/true
    B.b.     FAIL [255] lxc-usernsexec -mb:0:1000:1 -mb:1:100000:1 -- /bin/true

**Comment by stgraber** [comment]
@brauner do you still care about this?

**Review by hallyn — APPROVED** [review]
FWIW it looks good to me.  (But I didn't try rebasing onto main :)

**Comment by stgraber** [comment]
Okay, hopefully we can get @brauner to spend a few minutes rebasing on main at some point soon!

**Review by stgraber — APPROVED** [review]

**Pull request closed without merging**
