### PR TITLE
Fix typo in lxc-net script

### PR DESCRIPTION
**Pull request by adrian5**

### CODE REVIEW

**Comment by brauner** [comment]
Hi, you forgot to add a `Signed-off-by:` :)

**Comment by adrian5** [comment]
Sorry, I should have read the contribution notes first. I want to keep this Github account untied from my real-life identity if possible. If the signing policy is set in stone, then just close this pull request and create a new commit. It's not like I poured sweat and tears into it ;o

**Comment by brauner** [comment]
Just can just use your nic on GitHub and the forwarding email address that GitHub gives you to reply directly to you.

**Comment by brauner** [comment]
The email should look something like "reply@github-something.com". :)

**Comment by adrian5** [comment]
Ok, I tried to change it (not well versed in `git` yet), hope it's fine now.

**Comment by brauner** [comment]
@stgraber, all good DCO wise from your side?

**Pull request merged**
