### PR TITLE
Option to force lxc-copy and lxc-snapshot for running domains

### PR DESCRIPTION
**Pull request by Anthony25**
Hello,
This PR is linked with the issue #1254. It adds a flag to force the clone of a container, even if it is running.
The python API has not been touched, though.

### CODE REVIEW

**Comment by Anthony25** [comment]
Sorry about the tests failure, the needed changes in the Python API were not added.

**Comment by brauner** [comment]
I'm not convinced of this change. This will likely mean a lot of bug reports of inconsistent container clones and weird failures.

**Comment by stgraber** [comment]
You'd also need to sign-off your commit before we can consider it for inclusion. (See CONTRIBUTING)

**Comment by Anthony25** [comment]
@brauner: I agree, but personally I think that giving responsibility to the user is not a bad thing if they are aware about the possible dangers. Maybe some users might want to lock their database, make a snapshot/copy and then unlock their database, what would be safe but not possible right now.

@stgraber: Done, sorry about that.

**Comment by brauner** [comment]
As I said, I don't think this patch provides enough value. While I understand the problem we shouldn't just allow this. Especially given that this involves some internal change and given from what I've seen also an API break. Which is not a thing we do. :)

**Pull request closed without merging**
