### PR TITLE
configure: add --enable-fuzz

### PR DESCRIPTION
**Pull request by brauner**
Fixes: #3727
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by evverx** [comment]
@brauner thanks!

I wonder if it would be better to turn it off with something like `--disable-no-undefined` to make it possible to build lxc with sanitizers regarless of whether the fuzz targets are built or not? This way `--enable-asan` and `--enable-ubsan` could turn  that flag on automatically as well.

**Comment by brauner** [comment]
Oh yeah, that's a good point.

**Comment by evverx** [comment]
Looking at src/lxc/Makefile.am, it seems `liblxc_la_LDFLAGS` takes precedence over `AM_LDFLAGS`:
https://github.com/lxc/lxc/blob/65c5bc571b94345decd779092056c11981f6fea4/src/lxc/Makefile.am#L272-L275

The sed script removes -Wl,-no-undefined from there to compile liblxc on OSS-Fuzz as far as I can tell. Let me double check

**Comment by brauner** [comment]
Closing until we have a better way of dealing with this.

**Pull request closed without merging**
