### PR TITLE
static liblxc, always create /dev directory when autodev = 1, open("/dev/null") opportunistically

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>
Cc: Serge Hallyn <serge@hallyn.com>
Cc: Tycho Andersen <tycho@tycho.ws>

### CODE REVIEW

**Comment by brauner** [comment]
@stgraber, the change required to the packaging should just be:
```
diff --git a/debian/liblxc1.install b/debian/liblxc1.install
index 4df0e5c..dc0aa43 100644
--- a/debian/liblxc1.install
+++ b/debian/liblxc1.install
@@ -1,2 +1,3 @@
 usr/lib/*/*.so.*
+usr/lib/*/*.a
 usr/lib/*/lxc/README
```

**Comment by brauner** [comment]
@stgraber, @hallyn ready to go

**Comment by stgraber** [comment]
Why liblxc_static.a instead of liblxc.a? such _static suffix doesn't seem to be used by any other library on my system

**Comment by brauner** [comment]
@stgraber, no particular reason. I just thought it'd be more clear. But I've changed it to simply spew out an additional `liblxc.a` file. The diff for the deb should be:
```
diff --git a/debian/lxc-dev.install b/debian/lxc-dev.install
index 90d8c98..7ba5a40 100644
--- a/debian/lxc-dev.install
+++ b/debian/lxc-dev.install
@@ -1,3 +1,4 @@
 usr/include
 usr/lib/*/*.so
+usr/lib/*/*.a
 usr/lib/*/pkgconfig
```

**Comment by stgraber** [comment]
Merged and updated the packaging for the daily PPA.

**Pull request merged**
