### PR TITLE
lvm: check whether lxc.bdev.lvm.vg is empty

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
what's with the cgroup change?

**Comment by brauner** [comment]
@stgraber, it's just scoping the `int ret` declaration tighter which we do for other variables in this function as well.

**Comment by brauner** [comment]
I've introduced the wider-scoping variable in my other change for the gcc fix before.

**Comment by stgraber** [comment]
@brauner can you move it to a separate commit since it doesn't appear to have anything to do with lvm? :)

**Comment by brauner** [comment]
@stgraber, updated. :)

**Comment by stgraber** [comment]
If the intent was to fix the build failure on archlinux, this didn't work ;)

https://jenkins.linuxcontainers.org/view/All/job/lxc-template-archlinux/524/arch=amd64,release=current,restrict=lxc-priv,variant=default/console

**Pull request merged**
