### PR TITLE
log: add trace feature for liblxc

### PR DESCRIPTION
**Pull request by 0x0916**
When we use only `liblxc`, we have no way to get DEBUG/TRACE
information.

With this patch, we can set `LXC_TRACE=xxx`(xxx may be `trace`,`debug`,
`ifno`, `notice`, `warn` and `error` etc.). and then we can see more info
from stdout.

This is very useful for developers when they debug programs which only
use `liblxc`.

For example:

run lxc tests without `LXC_TRACE=trace`

```bash
$ ./src/tests/lxc-test-startone
all lxc_container tests passed for lxctest1
Destroyed container lxctest1
```

and run lxc tests with `LXC_TRACE=trace`

```bash
$ LXC_TRACE=trace ./src/tests/lxc-test-startone
[INFO] lxc: lsm/lsm.c: lsm_init: 62 Initialized LSM security driver AppArmor
[INFO] lxc: lsm/lsm.c: lsm_init: 62 Initialized LSM security driver AppArmor
[DEBUG] lxc: monitor.c: lxc_monitord_spawn: 330 Going to wait for pid 16607.
[DEBUG] lxc: monitor.c: lxc_monitord_spawn: 349 Trying to sync with child process.
[INFO] lxc: start.c: lxc_check_inherited: 243 Closed inherited fd: 3.
[INFO] lxc: start.c: lxc_check_inherited: 243 Closed inherited fd: 4.
[DEBUG] lxc: monitor.c: lxc_monitord_spawn: 364 Successfully synced with child process.
[DEBUG] lxc: monitor.c: lxc_monitord_spawn: 333 Finished waiting on pid 16607.
[INFO] lxc: lxccontainer.c: do_lxcapi_start: 802 Attempting to set proc title to [lxc monitor] /usr/local/var/lib/lxc lxctest1
[INFO] lxc: start.c: lxc_check_inherited: 243 Closed inherited fd: 3.
[DEBUG] lxc: monitor.c: lxc_monitord_spawn: 330 Going to wait for pid 16611.
[DEBUG] lxc: monitor.c: lxc_monitord_spawn: 349 Trying to sync with child process.
[INFO] lxc: start.c: lxc_check_inherited: 243 Closed inherited fd: 3.
[INFO] lxc: start.c: lxc_check_inherited: 243 Closed inherited fd: 4.
[DEBUG] lxc: monitor.c: lxc_monitord_spawn: 364 Successfully synced with child process.
[DEBUG] lxc: monitor.c: lxc_monitord_spawn: 333 Finished waiting on pid 16611.
[INFO] lxc: monitor.c: lxc_monitor_sock_name: 201 using monitor socket name "lxc/69d2cd1be5952f52//usr/local/var/lib/lxc" (length of socket name 43 must be <= 105)
[DEBUG] lxc: monitor.c: lxc_monitor_open: 225 opening monitor socket lxc/69d2cd1be5952f52//usr/local/var/lib/lxc with len 43
[DEBUG] lxc: commands.c: lxc_cmd_rsp_recv: 203 command get_state response data length is 0
[DEBUG] lxc: commands.c: lxc_cmd_get_state: 586 Container "lxctest1" is in "RUNNING" state.
[DEBUG] lxc: commands.c: lxc_cmd_rsp_recv: 203 command get_state response data length is 0
[DEBUG] lxc: commands.c: lxc_cmd_get_state: 586 Container "lxctest1" is in "RUNNING" state.
[DEBUG] lxc: commands.c: lxc_cmd_rsp_recv: 203 command get_state response data length is 0
[DEBUG] lxc: commands.c: lxc_cmd_get_state: 586 Container "lxctest1" is in "RUNNING" state.
[DEBUG] lxc: commands.c: lxc_cmd_rsp_recv: 203 command get_state response data length is 0
[DEBUG] lxc: commands.c: lxc_cmd_get_state: 586 Container "lxctest1" is in "RUNNING" state.
[DEBUG] lxc: commands.c: lxc_cmd_rsp_recv: 203 command get_state response data length is 0
[DEBUG] lxc: commands.c: lxc_cmd_get_state: 586 Container "lxctest1" is in "RUNNING" state.
[DEBUG] lxc: commands.c: lxc_cmd_rsp_recv: 203 command stop response data length is 0
[INFO] lxc: commands.c: lxc_cmd_stop: 632 Container "lxctest1" has stopped.
all lxc_container tests passed for lxctest1
[INFO] lxc: commands.c: lxc_cmd_stop: 617 Container "lxctest1" is already stopped.
[INFO] lxc: lsm/lsm.c: lsm_init: 62 Initialized LSM security driver AppArmor
Destroyed container lxctest1
```

Signed-off-by: 0x0916 <w@laoqinren.net>

### CODE REVIEW

**Comment by brauner** [comment]
I really don't think that this is needed. Users who want that should just make sure that they initialize a log file or set the log file to `/proc/self/fd/1`. For example:

    lxc-start -n c -l debug -o /proc/self/fd/1

**Comment by hallyn** [comment]
Right, since start-one appears to be a program you wrote using liblxc, why not simply use lxc_log_init()?  See src/lxc/tools/lxc_start.c for instance.

**Comment by 0x0916** [comment]
@brauner we can use `-l debug -o file` to set the log file, but,  in our project, we only install `liblxc` package, and have not install any `lxc-xxx` command. I think that it is a common issue when user developing their own software based on `liblxc`.

@hallyn yes, we can simply use `lxc_log_init()`, but it does not export by `liblxc`.

**Comment by hallyn** [comment]
> @hallyn yes, we can simply use `lxc_log_init()`, but it does not export by `liblxc`.

Ah!  Can we fix that?

**Comment by brauner** [comment]
If we expose `lxc_log_init()` we should make it have a sane interface and maybe even have it take a struct as an arg so we can easily expand it later. :)

**Comment by 0x0916** [comment]
@brauner @hallyn  I agree to expose function `lxc_log_init`, and I create a new issue(https://github.com/lxc/lxc/issues/1589) to track it.

**Pull request closed without merging**
