### PR TITLE
apparmor: don't fail if current aa label is given

### PR DESCRIPTION
**Pull request by hallyn**
Ideally a container configuration will specify 'unchanged' if
it wants the container to use the current (parent) profile.  But
lxd passes its current label.  Support that too.

Note that if/when stackable profiles exist, this behavior may
or may not be what we want.  But the code to deal with aa
stacking will need some changes anyway so this is ok.

With this patch, I can create nested containers inside a
lxd xenial container both using

lxc launch x2

and unprivileged

lxc-start -n x2

Signed-off-by: Serge Hallyn <serge.hallyn@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
I think the test suite failed due to network errors but I'm not completely sure so holding off the merge.

**Comment by brauner** [comment]
Nope, I was wrong, lxc-test-apparmor-mount fails.

**Comment by hallyn** [comment]
jenkins: test this please

**Comment by hallyn** [comment]
Previous patch had a flaw in its logic.  This one locally passes lxc-test-apparmor for me.  Which doesnt' mean I didn't break another testcase.

**Pull request merged**
