### PR TITLE
Fix swap calculation (#737)

### PR DESCRIPTION
**Pull request by ec-m**

### CODE REVIEW

**Comment by stgraber** [comment]
This pull request didn't trigger Jenkins as its author isn't in the whitelist.

An organization member must perform one of the following:

 - To have this branch tested by Jenkins, use the "ok to test" command.
 - To have a one time test done, use the "test this please" command.

Those commands are simple Github comments of the format: "jenkins: COMMAND"

**Comment by hallyn** [comment]
...  Well that took me awhile, but it all does look kosher :)

jenkins: test this please

**Comment by hallyn** [comment]
lxc-ls doesn't get tested, so no sense waiting.

**Comment by ec-m** [comment]
@hallyn Alright, thanks! Maybe we should close #737

**Comment by hallyn** [comment]
On Wed, Dec 23, 2015 at 03:01:01PM -0800, Eva Charlotte Mayer wrote:
> @hallyn Alright, thanks! Maybe we should close #737

oh, yeah - for future reference you can put "Closes #737" in the commit
msg to do that automatically.

**Comment by ec-m** [comment]
Perfect - good to know, I'll do that next time ;)

**Pull request merged**
