### PR TITLE
OCI layer caching + misc fixes

### PR DESCRIPTION
**Pull request by flx42**

### CODE REVIEW

**Comment by hallyn** [comment]
jenkins: test this please

**Comment by hallyn** [comment]
Thanks - patchset looks good.

**Comment by flx42** [comment]
Caching will be enabled by default with this patchset (provided skopeo is recent enough), is that fine for you?

**Comment by hallyn** [comment]
yeah i think it's good.  where does skopeo cache the images by default?

**Comment by flx42** [comment]
It doesn't, you need to use `dest-shared-blob-dir` with a path.
Previously, we downloaded all the layers to a temp directory.

**Pull request merged**
