### PR TITLE
Introducing lxc.console.buffer.rotate

### PR DESCRIPTION
**Pull request by duguhaotian**
#2088  add lxc.console.buffer.rotate

### CODE REVIEW

**Comment by duguhaotian** [comment]
@brauner I have two doubts.
First , now ,my implements, will let buffer log file increase, no limit. Do we need limit this file size less than  **lxc.console.buffer.size** ???
Second, **lxc.console.buffer.rotate** now is 0 or 1. Do we need let it big than 1???

**Comment by duguhaotian** [comment]
And this PR,  will make **write_logfile** function in **lxc_cmd_console_log_callback** meaningless. Because rotate always to do this when ringbuffer is full.

**Comment by duguhaotian** [comment]
Hi, is this patch necessary ? @brauner

**Comment by brauner** [comment]
I'm thinking about a different design for this but I want to discuss this with the other maintainers first. Basically, I'd like to introduce `lxc.console.size` and drop `lxc.console.buffer.logfile `entirely.

**Comment by brauner** [comment]
I'm working on a solution to this.

**Comment by brauner** [comment]
Closing in favor of https://github.com/lxc/lxc/pull/2167 .

**Pull request closed without merging**
