### PR TITLE
tests: fix oss-fuzz port to meson

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner (Microsoft) <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
@evverx any chance you can take a look and help figure out what's going wrong here?

**Comment by evverx** [comment]
Looks like `ASan` is linked statically somewhere. I'll try to take a closer look a bit later today.

FWIW `meson` isn't compatible with `fuzz-introspector` (https://github.com/systemd/systemd/pull/23158) so when this PR lands it will stop working.

**Comment by brauner** [comment]
> @brauner I got it to work with [513e678](https://github.com/lxc/lxc/commit/513e6782251bd9d95f56028f1058638d76215c54) on top of your PR. The idea is to link the fuzz targets statically against liblxc to avoid dealing with shared libraries in any way because they tend to break fuzz-introspector, CIFuzz and coverage reports.

Thank you!

**Comment by evverx** [comment]
@brauner it appears that `tests_common_sources` contains the liblxc sources so it seems it isn't necessary to link the fuzz targets against `liblxc` at all. I removed `link_with: [liblxc_static]` from the fuzz targets and they appear to be buildable locally with the OSS-Fuzz toolchain. I haven't tested it with CIFuzz though.

**Comment by evverx** [comment]
> I can send a follow-up PR and see how we can improve this.

Makes sense. In the meantime I opened https://github.com/google/oss-fuzz/pull/7841 to trigger the CI there to make sure this PR covers all the bases. https://github.com/google/oss-fuzz/actions/runs/2471355690 looks promising :-)

**Pull request merged**
