### PR TITLE
lxccontainer.c: Use calloc instead of malloc/memset

### PR DESCRIPTION
**Pull request by marcosps**
Signed-off-by: Marcos Paulo de Souza <marcos.souza.org@gmail.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Can you check that calloc also exists in bionic, uclibc and musl?

**Comment by marcosps** [comment]
@stgraber per my quick search, yes:

https://github.com/kraj/uClibc/blob/master/libc/stdlib/malloc/calloc.c
https://android.googlesource.com/platform/bionic/+/master/linker/linker_memory.cpp#74
https://github.com/rofl0r/musl/blob/master/src/malloc/calloc.c

Does lxc have some setup to test code compilation with different environments with such c libraries?

**Comment by stgraber** [comment]
We have tests for bionic, not for the others

**Comment by brauner** [comment]
We usually stay away from `calloc()` since it's interface is a little weird and it actually only provides performance benefits if you allocate quite a bit of memory usually at least around 1 MB or something. In this case `calloc()` employs `mmap()` to retrieve zeroed pages and also *can* reuse a single page as long as some memory is not touced. But for small allocations there's really not a difference. Even if `calloc()` is smart here and somehow avoids `memset()` work the `criu` codepath here needs to make very sure that the whole struct is set to 0 in case callers pass in a smaller struct. Furthermore the comments here match very well with the explicit `memset()`. So I'd prefer to nack this actually.

**Comment by marcosps** [comment]
@brauner ok, no problem. I'll try other places to contribute :)

**Comment by hallyn** [comment]
> @brauner ok, no problem. I'll try other places to contribute :)

Hi,

I hope you mean other places in the lxc code :)

**Comment by marcosps** [comment]
@hallyn sure, sorry for the dubious phrase. I liked the lxc idea, so I'm trying to learn more and to contribute with code and tests :)

**Pull request closed without merging**
