### PR TITLE
conf.c: add relative option for lxc.mount.entry

### PR DESCRIPTION
**Pull request by tanyifeng**
Signed-off-by: Yifeng Tan <tanyifeng1@huawei.com>

### CODE REVIEW

**Comment by brauner** [comment]
@stgraber, @hallyn, please share your thoughts. :)

**Comment by brauner** [comment]
And yes, technically you could do this with one of the mount hooks bug I think doing this in the config itself might be worth it.

**Comment by brauner** [comment]
So, @stgraber and I have discussed this today little bit and we think the correct solution is basically what I outlined in 1.:

`lxc.mount.entry` should gain an option `relative` which indicates that a given source is relative to the containers `lxc.rootfs.mount`. This would then let you specify:

    lxc.mount.entry = proc/kcore proc/kcore none bind,ro,relative 0 0

`liblxc` would then parse `relative` and see that  `proc/kcore` is taken to be relative to `lxc.rootfs.mount` and would expand this to (on Ubuntu) `/usr/lib/x86_64-linux-gnu/lxc/proc/kcore` and thus re-mount `/proc/kcore` read-only inside the container.
This requires that the mount entry setup in `lxc_setup()` be moved *after* filling the autodev otherwise you cannot do things like:

    lxc.mount.entry = /dev/null proc/kcore none,bind,ro,relative 0 0

without an additional `lxc.mount.entry` for `/dev/null`.

@stgraber, @hallyn how does that sounds?

**Comment by tanyifeng** [comment]
If we use `lxc.mount.entry`, how can we distinguish file and directories since we can not mount `/dev/null` to a file. Just like function `mask_path` do.

**Comment by brauner** [comment]
> If we use `lxc.mount.entry`, how can we distinguish file and directories since we can not mount `/dev/null` to a file. Just like function `mask_path` do.

In your original patch you detected it with `ENOTDIR` and then overmounted with a `tmpfs`? I would argue that if users want to mask paths they must know the reason for hiding those paths which usually should involve knowing whether it's a file or directory. :) If we hear a lot of complaints we can discuss adding another `liblxc` specific option.

**Comment by tanyifeng** [comment]
Sorry for the delay, I've changed the way of implementing option `relative` for `lxc.mount.entry` as you said.  It's a simply and reasonable way to resolve masked path and readonly path.  I'm not sure moving `setup_mount_entries` after `lxc_fill_autodev` is properly done or not. Please make sure that. Thanks.

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Thanks!

**Comment by brauner** [comment]
@tanyifeng, if you have a minute you could send a follow-up PR that makes the new `int relative` argument to `mount_entry() ` a `bool`. :)

**Pull request merged**
