### PR TITLE
Update Ubuntu release name: add zesty

### PR DESCRIPTION
**Pull request by Cypresslin**
Add zesty to KNOWN_RELEASES

Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Can you also remove wily since it's end of life?

**Comment by Cypresslin** [comment]
Ah, missed that, will do.

**Comment by Cypresslin** [comment]
Wily removed, thanks.

**Comment by brauner** [comment]
jenkins: test this please

**Pull request merged**
