### PR TITLE
apparmor: catch config file opening error

### PR DESCRIPTION
**Pull request by 4383**
Improve config file error opening management
and improve main code block.

Execute this python script during CI to avoid
regressions

Signed-off-by: Hervé Beraud <hberaud@redhat.com>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Thanks for the patch! :)

**Comment by stgraber** [comment]
Branch is breaking travis CI

**Comment by brauner** [comment]
Hm, the error is:
```

0.00s$ ./config/apparmor/lxc-generate-aa-rules.py config/apparmor/container-rules.base
/home/travis/.travis/functions: line 104: ./config/apparmor/lxc-generate-aa-rules.py: No such file or directory
The command "./config/apparmor/lxc-generate-aa-rules.py config/apparmor/container-rules.base" exited with 127.
```

**Comment by 4383** [comment]
I guess I need to `cd` to the root path since you move to `build`

**Comment by 4383** [comment]
Do you agree to add a sample output to compare generated file with him?
Compare to sample help us to avoid errors on this python script.

**Comment by brauner** [comment]
Sweet, thanks!

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
> Do you agree to add a sample output to compare generated file with him?
> Compare to sample help us to avoid errors on this python script.

I'd leave that for @stgraber to judge.

**Comment by stgraber** [comment]
Hmm, no, we shouldn't have a sample file to compare against, instead we should make sure that the generate file in the tree matches the source file, would also catch cases where someone changes the input but forgets to run the python script to generate a new set of rules.

**Comment by 4383** [comment]
@stgraber ack make sense

**Pull request merged**
