### PR TITLE
lxclock: remove atfork handlers

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

We'll remove the atfork handlers for now and let our LXD testsuite bang against LXC for a while to make sure that it is safe. But I've been reasoning about this for a while and I'm in the process of convincing myself that they are not needed anymore. In any case if we figure out they are needed we can simply revert before the release.

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by caglar10ur** [comment]
Just saw the patch in the mailing list :) I'm not up2date with the current state but I strongly suggest testing with ```lxc-test-concurrent -j 100``` or woth ```go-lxc/examples/concurrent* ```- that's how we tracked the original issue ~4 years ago.

**Comment by brauner** [comment]
@caglar10ur, yeah I've removed a bunch of internal locking and we haven't hit an issue and atfork handlers caused issues such that I had to replace fork() calls with low-level clone() calls. My idea is essentially in addition to testing this with the parameters you suggested to have the LXD testsuite bang on this. The LXD testsuite always runs against liblxc master once a branch is merged and it is massively heavy in terms of parallel container starts and so on. Once this runs clean for some time we'll consider making this a permanent change. If we hit any issues we'll simply revert. :)

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
@caglar10ur :)

```
lxc-test-concurrent -j 100 -i 20

Iteration 1/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 2/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 3/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 4/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 5/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 6/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 7/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 8/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 9/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 10/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 11/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 12/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 13/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 14/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 15/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 16/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 17/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 18/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 19/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...

Iteration 20/10 maxfd:3
Executing (create) for 100 containers...
Executing (start) for 100 containers...
Executing (stop) for 100 containers...
Executing (destroy) for 100 containers...
```

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Pull request merged**
