### PR TITLE
cgroups: improvements

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins not happy

**Comment by brauner** [comment]
> jenkins not happy

I'm very confused. That jenkins link shows me:
```
test-proc-sys test-proc-sys 20220113180006.206 DEBUG    conf - conf.c:lxc_allocate_ttys:989 - Created tty "/dev/pts/0" with master fd 11 and slave fd 14
```
and that "master"/"slave" terminology was removed ages ago... So this looks like the tests are running with a very outdated liblxc???

**Comment by brauner** [comment]
> > jenkins not happy
> 
> I'm very confused. That jenkins link shows me:
> 
> ```
> test-proc-sys test-proc-sys 20220113180006.206 DEBUG    conf - conf.c:lxc_allocate_ttys:989 - Created tty "/dev/pts/0" with master fd 11 and slave fd 14
> ```
> 
> and that "master"/"slave" terminology was removed ages ago... So this looks like the tests are running with a very outdated liblxc???

That log should read:
```
                DEBUG("Created tty with ptx fd %d and pty fd %d and index %d",
                      tty->ptx, tty->pty, pty_nr);
```

**Comment by stgraber** [comment]
Ah, I think I know what's going on, I'll fix it in a bit.

Basically we had some breakage earlier this week which I had to workaround by making our build environments use ubuntu:18.04 instead of images:ubuntu/18.04.

I suspect the Ubuntu image includes liblxc and is making this mess. Recovering back to our images should fix that now the the other issue has been resolved.

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
