### PR TITLE
coverity: #1425802

### PR DESCRIPTION
**Pull request by simos**
Resource leak

Signed-off-by: Simos Xenitellis <simos.lists@googlemail.com>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Needs a rebase.

**Comment by brauner** [comment]
Should be squashed into a single commit.

**Comment by simos** [comment]
I pushed a `Merge remote-tracking branch 'upstream/master'` commit at https://github.com/simos/lxc
which I think it should not be there. I did not find a way to get rid of it.
Is this recoverable? Should I remove the fork and start over?

I ended up clicking on the github button here to resolve the conflict and making a fix.
If there is another way to do this, do tell me.

**Comment by brauner** [comment]
I'll show you.

**Comment by brauner** [comment]
jenkins: test this please

**Pull request merged**
