### PR TITLE
Initial support for idmapped mounts

### PR DESCRIPTION
**Pull request by brauner**
```
lxc.rootfs.options = idmap=/path/to/user/ns/to/idmap/to
```

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
> jenkins: test this please

Currently we require the caller to pass us a path to a userns via:
```
lxc.rootfs.option = idmap=</path/to/userns>
```

I think in the future we also want to accept:
```
lxc.rootfs.option = idmap
```
where `idmap` without a path argument means that the caller's user namespace is supposed to be used.
But for that to work we need to rework how LXC starts the container a bit. I think it's a bit of work but not too much.

**Comment by stgraber** [comment]
Looks like the new options aren't documented.
Also does the same apply to additional mounts through `lxc.mount.entry`?

**Comment by brauner** [comment]
> Looks like the new options aren't documented.
> Also does the same apply to additional mounts through `lxc.mount.entry`?

It could but it doesn't just yet. It would require a larger rework how we setup those mounts.

**Comment by stgraber** [comment]
@brauner want to do a rebase and land this one?

**Comment by brauner** [comment]
Yep, rebased now!

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
