### PR TITLE
templates/ubuntu: conditionally move upstart ssh job, as it is now op…

### PR DESCRIPTION
**Pull request by xnox**
…tional.

Mimic the code from the debian template.

### CODE REVIEW

**Comment by brauner** [comment]
@xnox, thanks man. Saw my Launchpad comment? :) You need to sign-off your commit though. :)

**Comment by xnox** [comment]
@brauner no idea about launchpad. I manually re-run lxc autopkgtests to validate dropping resolvconf from important and noticed this error in the autopkgtest.

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
@xnox, ah cool. I was pinging you on a Launchpad thread. But the I guess the @-syntax doesn't work there. :)

**Comment by xnox** [comment]
@brauner yeah, on launchpad one needs to "subscribe" people on the right hand side, and then comment afterwords.....

**Pull request merged**
