### PR TITLE
start: remove utmp watch

### LINKED ISSUE #1616: kill utmp
in start.c

### PR DESCRIPTION
**Pull request by brauner**
Closes #1616.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by 0x0916** [comment]
also need to remove the line: https://github.com/lxc/lxc/blob/master/src/lxc/conf.h#L320

**Comment by hallyn** [comment]
Heh, about time.

**Comment by hallyn** [comment]
I'll merge when the other line @0x0916 pointed out is removed.  (please squash into one commit :)

**Comment by brauner** [comment]
@hallyn, @0x0916, updated.

**Pull request merged**
