### PR TITLE
coverity: bugfixes

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
@flx42, seems to work. :)

**Comment by flx42** [comment]
Nice! Some people also reference the coverity ID in the commit message.

**Comment by brauner** [comment]
Hm, might be worth it.

**Comment by stgraber** [comment]
My OCD is unhappy with your second commit, it's missing a # :)

**Comment by brauner** [comment]
@stgraber, oh thanks, that would've bugged me too in the commit tree. :)

**Comment by brauner** [comment]
Nothing wrong with coding-OCD. :)

**Pull request merged**
