### PR TITLE
templates: use correct cron version in alpine template

### PR DESCRIPTION
**Pull request by melato**
Signed-off-by: Alex Athanasopoulos <alex@melato.org>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Thanks! :)

**Comment by melato** [comment]
You are welcome.

Forgive my ignorance, this was my first time submitting a pull request.

I started using LXD last month, and I like it.
I migrated my dedicated server from OpenVZ to LXD,
and my Ubuntu 14.04 containers to Ubuntu 16.04 and Alpine 3.4.
There was a lot to learn, including ZFS, and Alpine Linux.

- Alex Athanasopoulos

**Comment by brauner** [comment]
That is quite alright. We're all doomed to learn forever anyway. :)

**Pull request merged**
