### PR TITLE
conf: improve mountinfo and config parsing

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
//Cc @graysky2, @joanbm

**Comment by graysky2** [comment]
@brauner - I build the latest commit from your https://github.com/brauner/lxc/tree/2020-11-16/fixes.  Are you expecting it to work under kernel version 5.9.8?  As a control, I tested it just now on the stable kernel but build that it did not start my target container
```

**Comment by graysky2** [comment]
Ah, I see you just rebased and force pushed.  I will rebuild.

**Comment by graysky2** [comment]
OK, same issue under 5.9.8 for me:
```
# lxc-start -n playtime -l TRACE -o log
lxc-start: symbol lookup error: /usr/lib/liblxc.so.1: undefined symbol: seccomp_notify_fd
```

**Comment by brauner** [comment]
> OK, same issue under 5.9.8 for me:
> 
> ```
> # lxc-start -n playtime -l TRACE -o log
> lxc-start: symbol lookup error: /usr/lib/liblxc.so.1: undefined symbol: seccomp_notify_fd
> ```

This might be a compilation issue where you compile in an env that has a libseccomp which supports the notify api vs an environment that doesn. Are you using LD_LIBRARY_PATH to load the compiled library?

**Comment by graysky2** [comment]
As a sanity check, if I build the official https://github.com/lxc/lxc/releases/tag/lxc-4.0.5 tagged version, I get the same error.

> This might be a compilation issue where you compile in an env that has a libseccomp which supports the notify api vs an environment that doesn't. Are you using LD_LIBRARY_PATH to load the compiled library?

I am not doing anything special to load the compiled binaries.  Just building them in a clean build root as I always do.  Interestingly, if I build outside of the clean build root, the resulting binaries work as expected.  The errors have to be a function of using a clean build root it seems.

Summary:
Build 4.0.5 in a build root = errors in compiled binaries.
Build 4.0.5 in my native env = fine.

**Comment by brauner** [comment]
> As a sanity check, if I build the official https://github.com/lxc/lxc/releases/tag/lxc-4.0.5 tagged version, I get the same error.
> 
> > This might be a compilation issue where you compile in an env that has a libseccomp which supports the notify api vs an environment that doesn't. Are you using LD_LIBRARY_PATH to load the compiled library?
> 
> I am not doing anything special to load the compiled binaries. Just building them in a clean build root as I always do. Interestingly, if I build outside of the clean build root, the resulting binaries work as expected. The errors have to be a function of using a clean build root it seems.
> 
> Summary:
> Build 4.0.5 in a build root = errors in compiled binaries.
> Build 4.0.5 in my native env = fine.

There's no difference between the libseccomp version in the build root and outside the build root?

**Comment by graysky2** [comment]
> There's no difference between the libseccomp version in the build root and outside the build root?

I see what's going on ... I routinely point my buildroot to use the packages in Arch's [testing] repo.  They have version 2.5.2 in there whereas 2.4.2 is in our stable repo.  So that's the issue.  Sorry for all the noise surrounding the builds.

Back on topic:  I just built https://github.com/brauner/lxc/commit/73abecb4196a4e718ce1f69b2b7067bdf3a8c57e and am running it fine under 5.9.8 and under 5.10.0-rc4.  I would conclude your modification fixed the problem.

**Comment by brauner** [comment]
> > There's no difference between the libseccomp version in the build root and outside the build root?
> 
> I see what's going on ... I routinely point my buildroot to use the packages in Arch's [testing] repo. They have version 2.5.2 in there whereas 2.4.2 is in our stable repo. So that's the issue. Sorry for all the noise surrounding the builds.

No problem at all, really! I've been bitten by this before too.

> 
> Back on topic: I just built [brauner@73abecb](https://github.com/brauner/lxc/commit/73abecb4196a4e718ce1f69b2b7067bdf3a8c57e) and am running it fine under 5.9.8 and under 5.10.0-rc4. I would conclude your modification fixed the problem.

They should. I've just fixed a bug in my patch. :)

**Comment by graysky2** [comment]
@stgraber @brauner - Thanks for the 24 hour turned around :+1: Do you guys plan a point release before 5.10 goes gold?  If not, I will suggest a cherry pick to Arch that will coincide with the release of 5.10 into our stable repos.

**Comment by brauliobo** [comment]
lxc is currently not working with kernel 5.10.3 on Arch for me @graysky2 

is this related to `conf - conf.c:lxc_setup:3316 - Failed to mount "/dev"` at https://www.raspberrypi.org/forums/viewtopic.php?t=288234&start=250#p1760925?

can you make a release please?

**Comment by graysky2** [comment]
@brauliobo - You have to use 5.10.4 or build lxc from the stable-4.0 branch: https://github.com/lxc/lxc/tree/stable-4.0

**Comment by brauliobo** [comment]
thanks @graysky2, it worked now with 5.10.10 :)

**Pull request merged**
