### PR TITLE
default to CentOS 7

### PR DESCRIPTION
**Pull request by evgeni**
Signed-off-by: Evgeni Golov <evgeni@debian.org>

### CODE REVIEW

**Comment by evgeni** [comment]
the commit is properly signed-off?!

**Comment by brauner** [comment]
Signed off your commit? ;)

**Comment by evgeni** [comment]
@brauner https://github.com/lxc/lxc/commit/420382d598fd477936e66bd6ef2cb5daaa84f706.patch looks pretty signed off for me? :)

**Comment by evgeni** [comment]
(jenkins just died: https://jenkins.linuxcontainers.org/job/lxc-github-pull-dco/1575/console)

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
