### PR TITLE
Pass zero to clone

### PR DESCRIPTION
**Pull request by tych0**
Here's some things I was thinking about on a plane while working on something else :)

### CODE REVIEW

**Comment by brauner** [comment]
That's what I added lxc_raw_clone for and we already use that in a bunch of places. lxc_clone is used for CLONE_VM and we want the stack.

**Comment by tych0** [comment]
On Thu, May 09, 2019 at 11:27:27AM -0700, Christian Brauner wrote:
> That's what I added lxc_raw_clone for and we already use that in a bunch of places. lxc_clone is used for CLONE_VM and we want the stack.

Huh? I don't think you do.

**Comment by brauner** [comment]
> On Thu, May 09, 2019 at 11:27:27AM -0700, Christian Brauner wrote: That's what I added lxc_raw_clone for and we already use that in a bunch of places. lxc_clone is used for CLONE_VM and we want the stack.
> Huh? I don't think you do.

So there's
[`lxc_raw_clone()`](https://github.com/lxc/lxc/blob/master/src/lxc/raw_syscalls.c#L36)
and
[`lxc_raw_clone_cb()`](https://github.com/lxc/lxc/blob/master/src/lxc/raw_syscalls.c#L105)
both rely on COW aka don't pass stack as `NULL`.

The default in `start` is to use `lxc_raw_clone_cb()`:
https://github.com/lxc/lxc/blob/master/src/lxc/start.c#L1766
and when you share namespaces we use `CLONE_VM` and `lxc_clone()` with a separate stack. `lxc_clone()` is used on purpose here
https://github.com/lxc/lxc/blob/master/src/lxc/start.c#L1753
as a `child_fn` it calls [`lxc_raw_clone_cb()`](https://github.com/lxc/lxc/blob/master/src/lxc/start.c#L1619) after it as attached to all namespaces.

In fact `lxc_clone()` is only used in a few places. In all other places it has been replaced by `lxc_raw_clone{_cb}()`. Even `attach()` calls `lxc_raw_clone()`. It's been like that for a long time. :)

**Comment by tych0** [comment]
On Thu, May 09, 2019 at 02:38:55PM -0700, Christian Brauner wrote:
> > On Thu, May 09, 2019 at 11:27:27AM -0700, Christian Brauner wrote: That's what I added lxc_raw_clone for and we already use that in a bunch of places. lxc_clone is used for CLONE_VM and we want the stack.
> > Huh? I don't think you do.
> 
> So there's
> [`lxc_raw_clone()`](https://github.com/lxc/lxc/blob/master/src/lxc/raw_syscalls.c#L36)
> and
> [`lxc_raw_clone_cb()`](https://github.com/lxc/lxc/blob/master/src/lxc/raw_syscalls.c#L105)
> both rely on COW aka don't pass stack as `NULL`.

Right, sorry, so you really do want a heap allocated stack in this
case. But you don't want it on your same stack.

I went ahead and updated the PR and the commit message to reflect
this.

**Comment by brauner** [comment]
Hm, you need to rebase. :) Why are you switching to using heap memory?

**Comment by tych0** [comment]
On Wed, May 15, 2019 at 06:41:50AM -0700, Christian Brauner wrote:
> Hm, you need to rebase. :) Why are you switching to using heap memory?

Sure, just rebased. See the commit message, there's a reasonble
writeup there.

**Comment by brauner** [comment]
Sweet! :)

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Pull request merged**
