### PR TITLE
tools/lxc_unshare: removed internal logging

### PR DESCRIPTION
**Pull request by AustinReichert**
Signed-off-by: AustinReichert <austinskyreichert@utexas.edu>

### CODE REVIEW

**Comment by marcosps** [comment]
Acked-by: Marcos Paulo de Souza <marcos.souza.org@gmail.com>

The current log system is strange and difficult to grasp what is really going on. Thanks for cleaning this up!

**Comment by brauner** [comment]
jenkins: test this please

**Comment by AustinReichert** [comment]
@marcosps Happy to help!

**Comment by brauner** [comment]
To clarify this right away: The internal logging stays as it is. @AustinReichert already knows this. :) We're only interested in kicking out the use of internal symbols from the tools. The logging calls are one part of this.

**Comment by brauner** [comment]
@marcosps, what do you mean? Each `lxc-*` tool takes a `-l/--logpriority` and `-o/--logfile` argument. So you can do:

    lxc-start -n <container-name> -l trace -o some-file

and then everything gets dumped to `some-file`. You can either do `man lxc-*` or `lxc-* --help` for each tool to see the available options.

**Comment by brauner** [comment]
If you want to have it print to stdour or stderr you could even do

    lxc-start -n <container name> -l trace -o /dev/std{out,err}

**Comment by marcosps** [comment]
@brauner I didn't notice this before... it wuold make my life easier :)

But, thanks for the tip, now I'm a fan of the internal logging 👍

**Pull request merged**
