### PR TITLE
fix fd handle leak

### PR DESCRIPTION
**Pull request by 2xsec**
Hello,

fix fd handle leak.

Thanks.

Signed-off-by: Donghwa Jeong <dh48.jeong@samsung.com>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Thanks, sorry it took longer. I overlooked the notification somehow. :)

**Comment by brauner** [comment]
Mere download failures.

**Comment by 2xsec** [comment]
That's OK^^

**Pull request merged**
