### PR TITLE
lxc_usernsexec: continuing after unshare fails leads to confusing and…

### PR DESCRIPTION
**Pull request by xmcqueen**
… misleading error messages

### CODE REVIEW

**Comment by xmcqueen** [comment]
That was a ridiculous effort for a three line commit! wow.  I'm glad its setup now. I think its right.  Getting the gpg key thing going right on this osx was not easy to figure out.

**Comment by brauner** [comment]
Ah, I think you misunderstood me. :) All we need is a DCO line at the end of your commit message like this:

Signed-off-by: Firstname Lastname <valid.email@address.com>

**Comment by brauner** [comment]
You can achieve this by doing:

got commit -s

**Comment by brauner** [comment]
The gpg part is useful too though so thanks for going through that hazzle. :)

**Comment by xmcqueen** [comment]
this is merged from a different PR

**Pull request closed without merging**
