### PR TITLE
tools: add UNPRIVILEGED field in fancy output mode

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
@hallyn, might not be worth it so feel free to nack it. Just found it helpful.

**Comment by hallyn** [comment]
Do you think this might mess up any people's scripts?  Shouldn't so long as it's appended as a new last column...

What about instead of 'unprivileged', showing the value to which container root is mapped?  Seems more useful, but maybe less new-user-friendly.

**Comment by brauner** [comment]
Ok, `aa_change_profile()` writes to `/proc`. Sigh...

**Comment by hallyn** [comment]
Ok technically since we (aim to) support containers without a root uid mapping, it seems useful to separately show 'unprivileged' and 'container root mapping'.  Illl merge this.

**Comment by brauner** [comment]
Oh sorry, I would've been happy to merge this I was just hadn't come around to it yet.

**Pull request merged**
