### PR TITLE
Fixes for analysed code

### PR DESCRIPTION
**Pull request by lunixoid**
I'm a member of the Pinguem.ru competition on finding errors in open source projects. A warning, found using PVS-Studio:
**Fixed conditions**
lxc/src/lxc/cgroups/cgfs.c  659     warn    V560 A part of conditional expression is always true: h.
lxc/src/lxc/cgroups/cgfs.c  1772    warn    V547 Expression 'proc_pid_cgroup' is always true.
lxc/src/lxc/start.c 1004    warn    V547 Expression 'devnull_fd >= 0' is always true.
**Fixed possible memory leak**
lxc/src/lxc/storage/rsync.c	77	err	V773 The function was exited without releasing the 's' pointer. A memory leak is possible.
lxc/src/lxc/lxccontainer.c	4407	err	V773 The function was exited without releasing the 'valid_opts' pointer. A memory leak is possible.

### CODE REVIEW

**Comment by brauner** [comment]
Hi, you need to sign-off your commit.

**Comment by brauner** [comment]
Sorry, this should be as simple as adding `Signed-off-by: Person Doe <person@doe.prefix>` to each of your commits. You should use a valid clear name and a valid email address. If in doubt, just look at already merged commits.

**Comment by lunixoid** [comment]
Commits updated. Is it correct now?

**Comment by brauner** [comment]
The easiest way would probably to create a new pr with all the fixes and a signed-off commit.

**Comment by brauner** [comment]
If you could create a new pr as a single commit with the fixes that would be great. Closing this one.

**Pull request closed without merging**
