### PR TITLE
log: support dlog

### PR DESCRIPTION
**Pull request by 2xsec**
Hello,

This patch is for supporting dlog to print logs.

It can be used on all tizen devices because tizen is using dlog for printing logs as default.

The default option is disable. In order to enable dlog, --enable-dlog option is needed.

Thanks.

Signed-off-by: 2xsec <dh48.jeong@samsung.com>

### CODE REVIEW

**Comment by brauner** [comment]
I have nothing against this patch in principle but can you point me to the dlog source code, please? I need to see the license.

**Comment by 2xsec** [comment]
@brauner The license is apache version 2.0. You can see the source codes of the dlog. :)
https://review.tizen.org/git/?p=platform/core/system/dlog.git;a=summary

**Comment by brauner** [comment]
Ok, then seems legit to me. If that's useful to you and you have it behind a compile flag, so be it. :)

**Comment by brauner** [comment]
jenkins: test this please

**Comment by 2xsec** [comment]
@brauner Thanks for understanding. :)

**Pull request merged**
