### PR TITLE
config: try to create workdir if not exist

### PR DESCRIPTION
**Pull request by xinhua9569**
Signed-off-by: dongxinhua <dongxinhua@huawei.com>

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@brauner @mihalicyn can either of you review this one for any problematic side-effects?

I'd probably reword the warning message and add a line-break before merging, but I can just do that if we're otherwise happy with it.

**Review by hallyn — APPROVED** [review]
You *could* also make sure that it's not a file, but this is good as is.

**Comment by stgraber** [comment]
Just one thing to fix:
```
../src/lxc/start.c: In function ‘do_start’:
../src/lxc/start.c:1330:63: error: implicit declaration of function ‘mkdir_p’; did you mean ‘mkdirat’? [-Werror=implicit-function-declaration]
 1330 |                 if (stat(handler->conf->init_cwd, &st) < 0 && mkdir_p(handler->conf->init_cwd, 0755) < 0) {
      |                                                               ^~~~~~~
      |                                                               mkdirat
../src/lxc/start.c:1330:63: warning: nested extern declaration of ‘mkdir_p’ [-Wnested-externs]
cc1: some warnings being treated as errors
```

**Comment by hallyn** [comment]
oh is that just bc mkdir_p has been renamed to lxc_mkdir_p ?

**Comment by stgraber** [comment]
Looks that way, yeah :)

**Comment by stgraber** [comment]
I've replaced mkdir_p with lxc_mkdir_p and added a line break between the two code blocks (it was bugging me). Let's see what Jenkins thinks of this now.

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
