### PR TITLE
meson: fix minor typo

### PR DESCRIPTION
**Pull request by tttuuu888**
Hi team, This PR is to fix issue #4492 . It simply corrects a typo.

### CODE REVIEW

**Comment by stgraber** [comment]
Hey @tttuuu888, looks like your commit is missing the required `Signed-off-by: Firstname Lastname <email>` line, see CONTRIBUTING

**Comment by tttuuu888** [comment]
Hi @stgraber, thank you for letting me know. It was not just about GPG signing, but the commit message also needs to include that information. I’ve just updated the commit. Thank you.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Thanks!

**Pull request merged**
