### PR TITLE
Rename and move physical interfaces at the same time

### PR DESCRIPTION
**Pull request by samboyles1**
We have come across an problem where containers fail to start because of an issue
when renaming physical interfaces to names of a similar pattern.

With a network config of:
    lxc.net.0.type = veth
    lxc.net.0.name = eth0
    lxc.net.0.flags = up
    lxc.net.0.link = br0
    lxc.net.0.vlan.id = 1
    lxc.net.0.hwaddr = ...
    lxc.net.1.type = phys
    lxc.net.1.name = eth1
    lxc.net.1.flags = up
    lxc.net.1.link = eth2
    lxc.net.2.type = phys
    lxc.net.2.name = eth2
    lxc.net.2.flags = up
    lxc.net.2.link = eth1

lxc will first rename vethXXXXX -> eth0, which is fine, but when it comes to
renaming eth2 -> eth1, it fails with:

ERROR  network - network.c:__instantiate_ns_common:883 - File exists - Failed to rename network device "eth2" to "eth1"
ERROR  network - network.c:lxc_setup_network_in_child_namespaces:3603 - File exists - Failed to setup netdev

It seems to be that lxc is confusing interface names in different network
namespaces when interfaces are being renamed.

This change makes it so that physical interfaces will be renamed at
the same time as they are moved into the containers network namespace.

Signed-off-by: Sam Boyles <sam.boyles@alliedtelesis.co.nz>
Signed-off-by: Blair Steven <blair.steven@alliedtelesis.co.nz>

### CODE REVIEW

**Comment by samboyles1** [comment]
There was a change made here fc0a8697b4a5a995e4863c48bda30fb6d805dc91 which meant the netdev->name wasn't provided to lxc_netdev_move_by_index, I am not 100% sure on the purpose of the change but it seems like phys devices are required to be moved into the container and renamed at the same time to avoid these collisions. Let me know if I have misunderstood anything.

**Review by brauner — APPROVED** [review]
I think this looks good. I'm not sure why this has happened.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
I'll be merging this tomorrow. I just need to take a close look how that codepath works and didn't get around today.

**Comment by samboyles1** [comment]
I may have found an issue with this but I'm having trouble figuring out if it's caused by this change or if I have mis-configured somewhere. I'll keep looking into it and let you know but maybe just hold off merging for the moment

**Comment by brauner** [comment]
I have a reproducer her so I'm starting to dig into this too. :) Thanks for finding that bug!

**Comment by brauner** [comment]
Oh, I see what's going on. :)

**Comment by brauner** [comment]
So we're first moving all the devices we created over:
```
lxc h2 20210226104629.455 DEBUG    network - network.c:lxc_network_move_created_netdev_priv:3418 - Moved network device "vethc4090546" with ifindex 22 to network namespace of 2375
lxc h2 20210226104629.910 DEBUG    network - network.c:lxc_network_move_created_netdev_priv:3418 - Moved network device "eth3" with ifindex 5 to network namespace of 2375
lxc h2 20210226104629.110 DEBUG    network - network.c:lxc_network_move_created_netdev_priv:3418 - Moved network device "eth2" with ifindex 4 to network namespace of 2375
```

Now we have all devices in the containers network namespaces and we're about to rename them:
```
veth<bla> -> eth0
eth3 -> eth2
eth2 -> eth3
```

But that obviously fails. :) We'd need to "swap" effectively. I think I know how to fix this.

**Pull request closed without merging**
