### PR TITLE
gcc -Wall flag compat

### PR DESCRIPTION
**Pull request by tomponline**
Builds on PR from @brauner https://github.com/lxc/lxc/pull/2886

I'm still working through these (the build still fails), but thought I would open in draft form early.

### CODE REVIEW

**Comment by tomponline** [comment]
@brauner @stgraber that should be all of them now, is now building with `-Wall` flag.

Is it possible to add this flag to the unit test compile?

**Comment by brauner** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
thanks @brauner 

Would there be any problem with adding an `export CFLAGS=-Wall` to https://github.com/lxc/lxc/blob/master/.travis.yml#L15

**Comment by brauner** [comment]
Should be already present by default:
```
https://github.com/lxc/lxc/blob/6400238d08cdf1ca20d49bafb85f4e224348bf9d/configure.ac#L43
```

**Comment by tomponline** [comment]
hrm interesting, I wonder why travis didn't fail the build, and it only failed on centos 7.

I wonder if it is to do with the interplay between `-Wall` and the other CFLAGS centos adds:

```
CFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic'
```

In my tests the other day, removing `-Wall` allowed it to compile with the other flags present. But perhaps using `-Wall` without the other flags also allows it to build.

I'll do a test an let you know.

**Comment by tomponline** [comment]
@brauner found it, AM_CFLAGS is defined in:

https://github.com/lxc/lxc/blob/1edf8fa48d82a1fe51d231e1d83e1c4bfea7e286/src/tests/Makefile.am#L44-L54

and

https://github.com/lxc/lxc/blob/1edf8fa48d82a1fe51d231e1d83e1c4bfea7e286/src/tests/Makefile.am#L44-L54

If I add the following arguments `-Wall -Werror -Wno-portability -Wall` to those lines, then the build fails when building on the commit https://github.com/lxc/lxc/commit/e613d684fa1757abe72d14ca5e39a08de3364285

So it doesn't look like the options in `AM_INIT_AUTOMAKE` are actually being used.

**Pull request merged**
