### PR TITLE
Kali Linux template for LXC (modified debian)

### PR DESCRIPTION
**Pull request by binkybear**
This is a modification of lxc-debian.in and debian template to support Kali Linux.  

Tested on Ubuntu 16.

Supports following issue: https://github.com/lxc/lxc/issues/140

Signed-off-by: binkybear <binkybear@nethunter.com>

### CODE REVIEW

**Comment by hallyn** [comment]
First, it seems you're re-enabling root password logins and re-setting the default root password of 'toor'.  I'd certainly prefer you drop that.

Also, looking at the diff between lxc-kali.in and lxc-debian.in, I can't help but feel we'd be better served with a more generalized lxc-debian-base.in which takes a few variables, and by default installs a debian system;  debian derivatives could then use it and make any other tweaks they need.

Maybe that actually doesn't work out long term as debian changes and derivatives do not...  But this sure seems like a lot of copied boilerplate which, if there is a security issue inherent in all of them, will need to be reproduced, probably be forgotten, hence not fixed.

So I guess this (commonality) is something for later discussion.  But please reply about the root password.

**Comment by binkybear** [comment]
@hallyn - By default in all Kali distributions the password is "toor" and it has always been that way (since Backtrack/before Kali).  Kali is not meant to be a "daily driver" and so by default it usually has SSH and default passwords set.

I see your point though in having to manage two different templates that are pretty much based off the same template.  Changes to Debian template may not necessarily make it into Kali template.

**Comment by hallyn** [comment]
Please make the default no password, with a --set-root-pwd option. I.e.

Lxc-create -t kali -n c1 -- --set-root-pwd

Will make toor the pwd

**Comment by hallyn** [comment]
Do you have any objections to my doing these changes for you?

**Comment by binkybear** [comment]
@hallyn - Sorry been a bit busy.  I have no objections if you have time to make changes.  Thank you!

**Comment by hallyn** [comment]
I've updated the template to follow the same env variables as lxc-fedora and lxc-centos (which I don't much like, but is better than having even more incompatible password schemes).  The result is in branch 'kali2' in github.com/hallyn/lxc.  Now when I try to use it, I get:

Installing packages:
chroot: failed to run command ‘apt-key’: No such file or directory
chroot: failed to run command ‘apt-get’: No such file or directory
chroot: failed to run command ‘apt-get’: No such file or directory

**Comment by hallyn** [comment]
So, to be clear, I'm leaving it at that, you can build on that or not, as you choose.

**Comment by brauner** [comment]
We've been keeping this PR around for a couple of months. I'm closing now but if you add another PR with the changes requested we won't object to merging.

**Pull request closed without merging**
