### PR TITLE
split bdev into modules: btrfs + rsync

### PR DESCRIPTION
**Pull request by brauner**
I'm currently working on splitting bdev.{c,h} into modules per block device for the liblxc 1.2 release. I'll push one or two modules at a time since the changes are quite substantial in terms of quantity and reviewing them would otherwise be a pain. We should probably take the opportunity to rename/rewrite some of the functions.

### CODE REVIEW

**Comment by stgraber** [comment]
This pull request didn't trigger Jenkins as its author isn't in the whitelist.

An organization member must perform one of the following:

 - To have this branch tested by Jenkins, use the "ok to test" command.
 - To have a one time test done, use the "test this please" command.

Those commands are simple Github comments of the format: "jenkins: COMMAND"

**Comment by brauner** [comment]
Note: The branch has already been marked as "ok to test" by Serge.

**Comment by brauner** [comment]
Even though rsync is not a bdev module it makes sense to take it out of bdev.{c,h} since it makes it obvious that there is al level of abstraction over all but also independent of all bdevs associated with it.

**Comment by hallyn** [comment]
Hi - iiuc, patch 5/6 (new naming for modules) should not exist - just update the previous commits to use the final names.  (unless there is a good reason not to due to the patch flow)

Otherwise basics look good, thanks.

**Comment by brauner** [comment]
@hallyn, done. It did involve some serious rebasing-skills. :)

**Comment by hallyn** [comment]
jenkins: test this please

**Comment by hallyn** [comment]
Manually merged (and fixed the spaces in Makefile)

**Comment by brauner** [comment]
I thought I fixed them already this morning. Hm, sorry.

**Comment by hallyn** [comment]
Oh - you might have.  I used the .patch I had fetched yesterday.

**Pull request merged**
