### PR TITLE
Add LUA api get_ips(), get_interfaces(), rename() functions

### PR DESCRIPTION
**Pull request by LynxChaus**

### CODE REVIEW

**Comment by stgraber** [comment]
This pull request didn't trigger Jenkins as its author isn't in the whitelist.

An organization member must perform one of the following:

 - To have this branch tested by Jenkins, use the "ok to test" command.
 - To have a one time test done, use the "test this please" command.

Those commands are simple Github comments of the format: "jenkins: COMMAND"

**Comment by stgraber** [comment]
Your commit isn't signed-off. Per CONTRIBUTING, please edit your commit message to include the required Signed-off-by line.

Thanks.

**Comment by LynxChaus** [comment]
Added Signed-off-by line.

**Comment by stgraber** [comment]
Looks like your branch needs rebasing so it gets down to a single commit :)

Alternatively, I can do that for you and apply the change locally, bypassing github.

**Comment by LynxChaus** [comment]
No problem, apply locally.

**Comment by stgraber** [comment]
Applied.

**Pull request closed without merging**
