### PR TITLE
monitor: report errno on exec() error

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
This is really minimal but given that we've now actually seen a monitor startup failure in https://github.com/lxc/lxd/issues/3255 we should log the `errno` associated with it.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Pull request merged**
