### PR TITLE
template: oci template supports for char user info

### PR DESCRIPTION
**Pull request by ssup2**
oci template changes character user info to uid, gid
according to OCI image spec.

Signed-off-by: Jungsub Shin jungsub_shin@tmax.co.kr

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
//Cc @flx42, @3XX0

**Comment by ssup2** [comment]
Oops, Sorry. Indent is wrong. Could I pull request again??

**Comment by brauner** [comment]
@ssup2, you can just force-push over this one. :)

**Comment by ssup2** [comment]
I make it the new request. thanks.

**Pull request closed without merging**
