### PR TITLE
apparmore: Improve testing on apparmor python script

### PR DESCRIPTION
**Pull request by 4383**
Compare command output to already existing container-rules file

Signed-off-by: Hervé Beraud <hberaud@redhat.com>

### CODE REVIEW

**Comment by 4383** [comment]
@stgraber changes related to your previous comment on #2847

**Comment by 4383** [comment]
Fixing commit message nit: change `apparmore` to `apparmor`

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Thanks! :)

**Pull request merged**
