### PR TITLE
Fix #520 - multiple instances of agetty on systemd.

### LINKED ISSUE #520: LXC 1.1.2 - container debian jessie : console usage issue
Hi

I compiled LXC for Debian Wheezy to use the latest stable version of LXC. with LXC 1.1.2, I encounteer problems to login in a Debian Jessie container. after typing lxc-console -n <container-name>

When I login my credentials are nearly always rejected, and sometimes, my password appears on the screen after I typed it.

Issuing the following command  "lxc-console -n tpl-deb8" should lead me in the console tty1 of my container, but it seems the console switch between two different terminals when I type the Enter key : tty1 and pts/0

Here is my console when I type several times this key without typing anyrhing : 

>Connected to tty 1
>Type <Ctrl+a q> to exit the console, <Ctrl+a Ctrl+a> to enter Ctrl+a itself
>
>Debian GNU/Linux 8 tpl-deb8 pts/0
>
>tpl-deb8 login: 
>Debian GNU/Linux 8 tpl-deb8 pts/0
>
>tpl-deb8 login: 
>Debian GNU/Linux 8 tpl-deb8 pts/0
>
>tpl-deb8 login: 
>Debian GNU/Linux 8 tpl-deb8 pts/0
>
>tpl-deb8 login: 
>Debian GNU/Linux 8 tpl-deb8 pts/0
>
>tpl-deb8 login: 
>Debian GNU/Linux 8 tpl-deb8 tty1
>
>tpl-deb8 login: 
>Debian GNU/Linux 8 tpl-deb8 tty1
>

I believe this cause my login attempts fails very often, cause a security issue when I type my password.
This bug does not appear with the LXC package provided in Debian Jessie itself.

EDIT : I can reproduce with the master branch too.

### PR DESCRIPTION
**Pull request by ar45**
Fixes issue with double tty login lxc-console
Ref #520, #484

This change set also allows for the initial config file to  specify the number of tty devices to create for the container.

### CODE REVIEW

**Comment by stgraber** [comment]
This pull request didn't trigger Jenkins as its author isn't in the whitelist.

An organization member must perform one of the following:

 - To have this branch tested by Jenkins, use the "ok to test" command.
 - To have a one time test done, use the "test this please" command.

Those commands are simple Github comments of the format: "jenkins: COMMAND"

**Comment by sim590** [comment]
Is this the complete fix ? I've tried it and I still experience #520 and #484.

**Comment by ar45** [comment]
I only fixed the debian template, not the arch one. #484 was closed by accident, because I referenced it from my commit.

**Comment by sim590** [comment]
Yes. I've just figured that out when looking at your solution. Are you going to fix it for arch too? If not, I guess I could quickly inspire from your solution and apply it to the arch template.

**Comment by ar45** [comment]
@sim590 I can do that later tonight. If you like, just go ahead and do it yourself.

**Comment by sim590** [comment]
I've just been looking at it and I must say I'm not familiar with the procedure of initializing getty... Plus, the issue seems diffrent from the one in debian template. I'll let the pros do the good work ;).

**Pull request merged**
