### PR TITLE
Created Pentoo LXC & Sabayon LXC types

### PR DESCRIPTION
**Pull request by necrose99**
they require a Gentoo container to build,  add on a few overlay repos and toys etc...
I'm tinkering with them however my code Foo is week/rusted up 
Pentoo is a flavor of Gentoo focased on bleeding edge, they are pre-alpha atm , however take a hack at them hopefully they prove useful.... 

Sabayon has equo & Entropy Package manager that rides atop Gentoo/portage, has often testing but stable packages ie kde5 and bleeding edge new stuff , as well has a rigo/gui for x to aid novice users in managing packages. 
mainly a few functions to call lxc-gentoo create the pentoo-{$arch}  or Sabayon-{$arch} 
currently only amd64 is supported-officially , however for legacy users such a container would and our CI would allow them to build new packages https://github.com/Spike-Pentesting/App-witchcraft or as well tinker in dangerous waters also not officially supported.. 

https://raw.githubusercontent.com/necrose99/lxc/master/templates/lxc-sabayon.in
https://raw.githubusercontent.com/necrose99/lxc/master/templates/lxc-pentoo.in

I may need to re-sync lxc/lxc and retry latter but feal free to fork mine and improve them.

### CODE REVIEW

**Comment by stgraber** [comment]
Ouch, that branch is a bit messy :)

Can you rebase your branch, make sure that it builds (currently doesn't according to Travis) and squash some of your commits together so it's easier to review?

**Comment by stgraber** [comment]
Oh and per CONTRIBUTING.md, all LXC commits must be signed-off with the Signed-off-by line, so you'll want to update them for that too.

Thanks!

**Comment by necrose99** [comment]
no problem i've been getting them as ready as i can, 
hopefully you can tweak them more but they just make a Gentoo container and then , just add in overlays, they use gentoo-lxc as a depend , however your welcome to carry them further (and your skills greatly exceed mine)  rig gentoo-lxc keep a few values safe copied , chroot do a few commands into container. (and your likely to have a much better log run fix than I, however K.I.S.S.....) 
Sabayon can often be a bit easier to admin than the stock Gentoo. 
but i have a few drive snags so son as i deal with the rolling updates to fix the issues. 

atm I'm trying to de-cruft my code into neat callable functions, thus any custom my-lxc can just call them, in someone elses script.

**Comment by stgraber** [comment]
Hmm, your branch is still a bit of a mess of commits, it also doesn't pass basic testing and currently can't be merged. Any hope of fixing those issues?

**Comment by necrose99** [comment]
been packing for TX move 
also since $$ is tied up on the moving expenses... I've had to forestall getting a replacement SSHD/SSD  
Gentoo compiles+ github has made laptop drives hdd life to about 9 months, 
plus i made a few browser based commits ,  
for now I have the old drive out and waiting to clone and repair the FS.... 
making a mention credits @ my name is fine enough if you take  file/s directly into your own commit ...

so far I've had to put a number of projects on hold,  I wish github would add web-stash.... IE save without committing or appending to a existing....  , or a means of squashing commits forward. i'm a tinkerer/IT-Security researcher  , not so much a dev... some of the gui clients could make this easier , however dont exactly make git squashing so simple .... or intuitive ... 

as well I need to take the scripts from a preemptive sharing to devs to validated/working.... status 
testing them in virtual box installs is also kinda a pain; as the Gentoo install floods , and running under windows.... slow... 
not having a fat server drive to really .....test them .... thoroughly.  is also kinda of pain....

**Comment by stgraber** [comment]
Branch is still messy and it doesn't apply, closing for now. Please re-submit a cleaner version (no merge commits!) and I'll review.

**Pull request closed without merging**
