### PR TITLE
cgroups: flatten hierarchy

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by chobostar** [comment]
Is that part should be fixed too ?
https://github.com/lxc/lxc/blob/master/configure.ac#L487-L490

**Comment by brauner** [comment]
> @brauner Is that part should be fixed too ?
> https://github.com/lxc/lxc/blob/master/configure.ac#L487-L490

Yep, looks like it. You want to give it a shot?

**Comment by brauner** [comment]
Otherwise I can send a pr once I'm back.

**Comment by chobostar** [comment]
https://github.com/lxc/lxc/pull/3259

**Pull request merged**
