### PR TITLE
lxccontainer: fix container creation error paths

### PR DESCRIPTION
**Pull request by brauner**
Fixes: #3782
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
You've compiled with `flto`?

**Comment by evverx** [comment]
I built it with
```
./autogen.sh &&
CFLAGS=-fsanitize=address,undefined ./configure --enable-tests --prefix=/usr/ --sysconfdir=/etc/ --localstatedir=/var/ --disable-no-undefined &&
make -j$(nproc)
```
and by default `-flto=thin` is passed to the compiler/linker as far as I can see

**Comment by brauner** [comment]
I wonder if it's related to `lto` and I've messed up the Makefile at some point. I do have an item to rework the testsuite on my TODO.

**Comment by evverx** [comment]
> I wonder if it's related to lto

I think it could be. FWIW I can't reproduce the crash with neither clang nor newer versions of gcc.

**Pull request merged**
