### PR TITLE
Added 'mkdir -p' functionality in create_or_remove_cgroup

### PR DESCRIPTION
**Pull request by rjmccabe3701**
This allows us to run LXC containers from within docker

### CODE REVIEW

**Comment by hallyn** [comment]
Hi,

Was there a reason not to use mkdir_p from utils.c?

**Comment by rjmccabe3701** [comment]
@hallyn: No reason at all, I'll make the change.

**Comment by brauner** [comment]
jenkins: test this please.

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
