### PR TITLE
tools: lxc-unshare: use lxc list for interface names

### PR DESCRIPTION
**Pull request by 2xsec**
Hello,

change legacy codes for managing interface names.

Thanks.

Signed-off-by: 2xsec <dh48.jeong@samsung.com>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
I think the prior patch made coverity slighlty sad. Can you take a look? :)

**Comment by 2xsec** [comment]
@brauner oh...ok

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Thanks! 😁

**Pull request merged**
