### PR TITLE
tree-wide: hide unnecessary symbols

### PR DESCRIPTION
**Pull request by brauner**
Do it file-by-file until we switch to `-fvsibility=hidden`.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
clang on travis isn't happy

**Comment by brauner** [comment]
> clang on travis isn't happy

clang should be happy now :)

**Comment by stgraber** [comment]
@brauner would you mind splitting into two PRs so I can review the mechnical hidding of unnecessary symbols separately from the mount API?

**Comment by brauner** [comment]
> @brauner would you mind splitting into two PRs so I can review the mechnical hidding of unnecessary symbols separately from the mount API?

Yeah, I just wanted to avoid the rebase for now. :) Sure will do.

**Comment by brauner** [comment]
> > @brauner would you mind splitting into two PRs so I can review the mechnical hidding of unnecessary symbols separately from the mount API?
> 
> Yeah, I just wanted to avoid the rebase for now. :) Sure will do.

Done now!

**Pull request merged**
