### PR TITLE
Setup libtool

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Looks like the python part needs a bit more tweaking.

**Comment by stgraber** [comment]
Not quite there yet, lua looks unhappy still...

**Comment by brauner** [comment]
Ah, having fun with `libtool`. Nothing more exciting...

**Comment by stgraber** [comment]
Yeah... that's needed to build on Ubuntu 17.04 unfortunately so I'm converting lxc over to it which is a lot more complicated than it should be (python3 and lua are a bit problematic there...).

**Comment by stgraber** [comment]
Current issue I'm fighting is related to the library version in the elf header, so fixing that with -version-info now, hopefully that'll fix things for good.

**Pull request merged**
