### PR TITLE
[lxc-top] Add memory+swap monitoring

### PR DESCRIPTION
**Pull request by anevenchanniy**
This is patch add memory + swap monitoring from lxc-top tool

### CODE REVIEW

**Comment by brauner** [comment]
Can you please show sample output of `lxc-top` with your patch applied?

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Your patch is missing a `Signed-off-by` line which we require. You can add one by doing `git commit -s ...`.

**Comment by anevenchanniy** [comment]
@brauner 
>
memsw

**Comment by brauner** [comment]
jenkins: test this please

**Pull request merged**
