### PR TITLE
Set c to NULL after freeing it

### PR DESCRIPTION
**Pull request by caglar10ur**
Signed-off-by: S.Çağlar Onur <caglar@10ur.org>

### CODE REVIEW

**Comment by brauner** [comment]
Thanks!

**Comment by 2xsec** [comment]
@caglar10ur 'c' is local variable in lxc_container_free function. Is there any reason for setting variable 'c'?

**Comment by caglar10ur** [comment]
@2xsec 'c' is a reference to the container struct

**Comment by Blub** [comment]
Since this isn't the first commit of the sort: `c` is in fact a local variable here. The data it pointed to was freed in the line above and it goes out of scope afterwards, which means it will not be used anymore. The added line is unnecessary.

**Comment by brauner** [comment]
> Since this isn't the first commit of the sort: `c` is in fact a local variable here. The data it pointed to was freed in the line above and it goes out of scope afterwards, which means it will not be used anymore. The added line is unnecessary.

Feel free to send a revert. :)

**Pull request merged**
