### PR TITLE
container start: clone newcgroup immediately

### PR DESCRIPTION
**Pull request by hallyn**
rather than waiting and later unsharing.

This "makes the creation of a new cgroup early enough that the existing
cgroup mounts are visible.  Which means any fancy permission checks
I dream will work on a future version of liblxc."

This also includes what should be a tiny improvement regarding netns,
though it's conceivable it'll break something.  Remember that with new
kernels we need to unshare netns after we've become the root user in the
new userns, so that netns files are owned by that root.  But we were
passing the unfiltered handler->clone_flags to the original clone().
This just resulted in a temporary extra netns generation, but still
worked since our target netns, which we passed our devices into, was
created late enough.

Signed-off-by: Serge Hallyn serge@hallyn.com
Signed-off-by: "Eric W. Biederman" ebiederm@xmission.com

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Marking this one blocked given that the kernel blows up when it's merged :)

Any idea of what's the kernel issue with this?

**Comment by stgraber** [comment]
@hallyn did we ever figure out wth was going on in the kernel?

**Comment by hallyn** [comment]
Quoting Stéphane Graber (notifications@github.com):
> @hallyn did we ever figure out wth was going on in the kernel?

No.  And I haven't tested with latest kernels.

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Calling this. :D

**Comment by tych0** [comment]
This breaks things for me. I end up with:

```
lxc shell zest
Last login: Thu Nov  3 18:07:17 UTC 2016 on UNKNOWN
run-parts: /etc/update-motd.d/98-fsck-at-reboot exited with return code 1
mesg: ttyname failed: Success
root@zest:~# ps auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        24  0.0  0.1  72068  3320 ?        Ss   18:11   0:00 login -f
root        70  0.0  0.2  21192  5000 ?        S    18:11   0:00  \_ -bash
root        85  0.0  0.1  36336  3240 ?        R+   18:11   0:00      \_ ps auxf
root         1  0.0  0.1  54064  2796 ?        Ss   18:11   0:00 /sbin/init
root@zest:~# cat /proc/1/cgroup 
11:memory:/../lxc/zest
10:perf_event:/lxc/zest
9:cpuset:/lxc/zest
8:net_cls,net_prio:/lxc/zest
7:pids:/../../../lxc/zest
6:cpu,cpuacct:/../lxc/zest
5:blkio:/../lxc/zest
4:hugetlb:/lxc/zest
3:freezer:/lxc/zest
2:devices:/../lxc/zest
1:name=systemd:/../../../lxc/zest
```

**Pull request merged**
