### PR TITLE
improve detect_ramfs_rootfs() and add test

### PR DESCRIPTION
**Pull request by brauner**

### CODE REVIEW

**Comment by brauner** [comment]
ping @hallyn. :)

**Comment by brauner** [comment]
ping @hallyn, @stgraber.

**Comment by hallyn** [comment]
Looks good, thanks.  (Only comment would be I see no point in returning to the initial namespace at the end of the testcase :)

**Comment by brauner** [comment]
> Looks good, thanks. (Only comment would be I see no point in returning to the initial namespace at the end of the testcase :)

In case other tests we might add later require a non-overmounted `/proc/self/mountinfo`. :)

**Pull request merged**
