### PR TITLE
[RFC] meson: link dynamically

### PR DESCRIPTION
**Pull request by mihalicyn**
Dear friends,

I noticed that LXC compilation time is too big and when I started looking closely into how we build tools/commands binaries I was surprised. It turned out that effectively each lxc tool is just build with *all* liblxc C files and then linked dynamically to liblxc, which is pointless. Final binary sizes are just the same as liblxc so-file. Compilation time is also quite big.

I have tried to make changes as small as it possible, I don't like moving functions between different C files because it makes `git blame` useless.

It would be great to hear as many opinions as possible as this change is kinda global and potentially can break something.
cc @lxc/lxc @tych0 

Some stats.

```
meson setup build -Dtests=true -Dpam-cgroup=false -Db_lto_mode=default -Dtools-multicall=true -Dprefix=/usr
time ninja -C build
```

Compilation time on machine with `AMD Ryzen 7 PRO 6850H` (8 cores 16 threads) and 64 GiB of RAM.
Before:
```
real	1m20.717s
user	15m48.934s
sys	3m16.254s
```
After:
```
real	0m20.434s
user	3m52.497s
sys	0m54.098s
```

LXC tools sizes.
Before:
```
-rwxrwxr-x  1 ubuntu ubuntu 4.0M Feb 18 16:42 lxc
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:41 lxc-attach
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:41 lxc-autostart
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:41 lxc-cgroup
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:41 lxc-checkpoint
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:41 lxc-config
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:41 lxc-console
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:41 lxc-copy
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:41 lxc-create
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:41 lxc-destroy
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:41 lxc-device
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:42 lxc-execute
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:42 lxc-freeze
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:42 lxc-info
-rwxrwxr-x  1 ubuntu ubuntu 3.6M Feb 18 16:42 lxc-ls
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:42 lxc-monitor
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:42 lxc-snapshot
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:42 lxc-start
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:42 lxc-stop
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:42 lxc-top
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:42 lxc-unfreeze
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:42 lxc-unshare
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:42 lxc-wait
```
After:
```
-rwxrwxr-x  1 ubuntu ubuntu 4.1M Feb 18 16:45 lxc
-rwxrwxr-x  1 ubuntu ubuntu 608K Feb 18 16:45 lxc-attach
-rwxrwxr-x  1 ubuntu ubuntu 607K Feb 18 16:45 lxc-autostart
-rwxrwxr-x  1 ubuntu ubuntu 598K Feb 18 16:45 lxc-cgroup
-rwxrwxr-x  1 ubuntu ubuntu 605K Feb 18 16:45 lxc-checkpoint
-rwxrwxr-x  1 ubuntu ubuntu 580K Feb 18 16:45 lxc-config
-rwxrwxr-x  1 ubuntu ubuntu 598K Feb 18 16:45 lxc-console
-rwxrwxr-x  1 ubuntu ubuntu 619K Feb 18 16:45 lxc-copy
-rwxrwxr-x  1 ubuntu ubuntu 604K Feb 18 16:45 lxc-create
-rwxrwxr-x  1 ubuntu ubuntu 601K Feb 18 16:45 lxc-destroy
-rwxrwxr-x  1 ubuntu ubuntu 600K Feb 18 16:45 lxc-device
-rwxrwxr-x  1 ubuntu ubuntu 599K Feb 18 16:45 lxc-execute
-rwxrwxr-x  1 ubuntu ubuntu 598K Feb 18 16:45 lxc-freeze
-rwxrwxr-x  1 ubuntu ubuntu 606K Feb 18 16:45 lxc-info
-rwxrwxr-x  1 ubuntu ubuntu 629K Feb 18 16:45 lxc-ls
-rwxrwxr-x  1 ubuntu ubuntu 3.5M Feb 18 16:45 lxc-monitor
-rwxrwxr-x  1 ubuntu ubuntu 601K Feb 18 16:45 lxc-snapshot
-rwxrwxr-x  1 ubuntu ubuntu 604K Feb 18 16:45 lxc-start
-rwxrwxr-x  1 ubuntu ubuntu 599K Feb 18 16:45 lxc-stop
-rwxrwxr-x  1 ubuntu ubuntu 609K Feb 18 16:45 lxc-top
-rwxrwxr-x  1 ubuntu ubuntu 598K Feb 18 16:45 lxc-unfreeze
-rwxrwxr-x  1 ubuntu ubuntu 612K Feb 18 16:45 lxc-unshare
-rwxrwxr-x  1 ubuntu ubuntu 598K Feb 18 16:45 lxc-wait
```

It is not an ideal result at all (ideally each tool should be 100 KiB not bigger!). But I think it's a good first step.

This is attempt to fix:
https://github.com/lxc/lxc/issues/4251
https://github.com/lxc/lxc/issues/4249
https://github.com/lxc/lxc/issues/4335

### CODE REVIEW

**Comment by stgraber** [comment]
Oh, that's great! Definitely fixes one of the big issues we got out of the switch to meson.

@brauner can you review? I guess we mostly want to make sure we don't end up exporting anything we don't intend to as a result of any of the reshuffling.

**Comment by mihalicyn** [comment]
> I guess we mostly want to make sure we don't end up exporting anything we don't intend to as a result of any of the reshuffling.

Yep. List of un-hidden functions:
```
int lxc_config_define_add(struct lxc_list *defines, char *arg);
bool lxc_config_define_load(struct lxc_list *defines, struct lxc_container *c);
void lxc_config_define_free(struct lxc_list *defines);

int lxc_config_parse_arch(const char *arch, signed long *persona);

bool lxc_is_valid_storage_type(const char *type);
```

**Comment by mihalicyn** [comment]
We have failures of "Fuzzing with OSS-fuzz / Fuzzing (address) (push)" https://github.com/lxc/lxc/actions/runs/7952024147/job/21706144749
I'll take care of it.

**Comment by mihalicyn** [comment]
https://github.com/lxc/lxc/pull/4403

**Comment by mihalicyn** [comment]
I'm not sure, but I think we can also start linking lxc multicall binary dynamically too (see https://github.com/lxc/lxc/pull/4149)

cc @petris

**Comment by petris** [comment]
I think it's not a problem to link the multicall binary dynamically, but if the intention is to save the size, wouldn't it make more sense to use the multicall binary setup as default and create links for backward compatibility (-Dtools=false -Dtools-multicall=true)? We have it deployed like that since I submitted the change and so far it's working fine.

**Pull request merged**
