### PR TITLE
confile: prepare for 2.1.

### PR DESCRIPTION
**Pull request by brauner**

### CODE REVIEW

**Comment by brauner** [comment]
@0x0916, it would probably a good idea to wait for @hallyn to merge this PR otherwise you very likely have to resolve a bunch of merge conflicts.

**Comment by 0x0916** [comment]
@brauner ok

**Comment by hallyn** [comment]
Perhaps we should (1) add a 'lxc.version' container config tag, and then ship tiny programs or sed scripts that can update container config versions.

**Comment by brauner** [comment]
@hallyn, yes that sounds like a good idea. Well, I'd like to discuss this in a little more depth and this pr is not the best location I'll make a Github issue and drag you into the discussion. :D

**Pull request merged**
