### PR TITLE
Split bdev into modules

### PR DESCRIPTION
**Pull request by brauner**
*I'm currently working on splitting bdev.{c,h} into modules per block device for the liblxc 1.2 release. The original plan was to only push one or two modules at the time but since the liblxc 1.2 release is due soon and I'm not sure whether this will be included or not I'll push everything onto this branch.*

IMPORTANT notes regarding the lvm-splitout:
In order to further split bdev.{c,h} into modules functions like:

    - int blk_getsize(struct bdev *bdev, uint64_t *size);
    - int detect_fs(struct bdev *bdev, char *type, int len);
    - int do_mkfs(const char *path, const char *fstype);
    - int is_blktype(struct bdev *b);
    - int mount_unknown_fs(const char *rootfs, const char *target,
	    	const char *options);

have to be made public (easiest solution I think). If we don't want them to be available to implementations that use bdev.h we might want to put these into a separate implementation- and header-file (e.g. bdev_utils.{c,h}) which can be included in bdev.c, lxclvm.c, lxcloop.c etc. Or we just keep it as I currently do it.

### CODE REVIEW

**Comment by stgraber** [comment]
This pull request didn't trigger Jenkins as its author isn't in the whitelist.

An organization member must perform one of the following:

 - To have this branch tested by Jenkins, use the "ok to test" command.
 - To have a one time test done, use the "test this please" command.

Those commands are simple Github comments of the format: "jenkins: COMMAND"

**Comment by stgraber** [comment]
jenkins: ok to test

**Comment by brauner** [comment]
Sorry, I can't make sense of the shell-output from Jenkins:

```
==> Exitting with status PASS
[lxc-trigger-github-pr@2] $ /bin/sh -xe /tmp/hudson4400571325882892285.sh
+ export JENKINS_URL=http://jenkins01.srv.mtl:8080
+ java -jar /lxc/deps/jenkins-cli.jar -i /lxc/deps/credentials build lxc-dispatch-tests -s -p parent=https://jenkins.linuxcontainers.org/job/lxc-trigger-github-pr/19/ -p lxc.tar.gz=lxc.tar.gz
Started lxc-dispatch-tests #1251
Completed lxc-dispatch-tests #1251 : FAILURE
Build step 'Execute shell' marked build as failure
Archiving artifacts
Notifying endpoint 'HTTP:https://linuxcontainers.org/webhook-lxcbot/'
Setting status of a44253a7a1e91fe4f17fe4edd719cb532d2276e0 to FAILURE with url https://jenkins.linuxcontainers.org/job/lxc-trigger-github-pr/19/ and message: 'Build finished. No test results found.'
Using context: Jenkins
[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
Finished: FAILURE
```

In case I need to fix anything you need to tell me what's wrong first.

**Comment by stgraber** [comment]
Nothing to worry about, failed on gcc/amd64, gcc/i386, clang/amd64 and clang/i386, succeeded on gcc/armhf, gcc/ppc64el and clang/armhf.

The failures were all network related or occasional kernel race conditions, nothing that can be linked to your proposed changes.

**Comment by brauner** [comment]
@stgraber, @hallyn, before making (substantial) changes to current `bdev.{c,h}` consider merging/reviewing this PR. Otherwise I'll have to manually resolve all sorts of merge conflicts.

**Comment by hallyn** [comment]
Oh I'd been waiting for this one.

**Comment by brauner** [comment]
It's been there for some time. :)

**Comment by hallyn** [comment]
Thanks @brauner !

**Pull request merged**
