### PR TITLE
fix assignment of signed to bigger unsigned issue

### PR DESCRIPTION
**Pull request by 2xsec**
Hello,

Fix assignment of a signed value which has type 'int' to a variable of a bigger integer type 'unsigned long' issue.

Thanks.

Signed-off-by: 2xsec <dh48.jeong@samsung.com>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by 2xsec** [comment]
@brauner Some build errors are fixed. I'm sorry. :)

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
np :)

**Comment by brauner** [comment]
Thanks.

**Pull request merged**
