### PR TITLE
coverity: bugfixes

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
10 quick coverity fixes a day keep segfaults away

**Comment by brauner** [comment]
@stgraber, good to go.

**Comment by hallyn** [comment]
Thanks, look good.

**Comment by hallyn** [comment]
(I seem to be missing a comment by @stgraber so will wait for him to merge if he's happy with it)

**Comment by brauner** [comment]
@hallyn what comment? :)

**Pull request merged**
