### PR TITLE
Add loongarch64 support

### PR DESCRIPTION
**Pull request by zhaixiaojuan**
The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has a RISC style.

Documentations:
ISA:
https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html
ABI:
https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html
More docs can be found at:
https://loongson.github.io/LoongArch-Documentation/README-EN.html

### CODE REVIEW

**Comment by mihalicyn** [comment]
jenkins: ok to test

**Comment by mihalicyn** [comment]
Hi @zhaixiaojuan !

Thanks for your work on the loongarch64 port for LXC.

Couldn't you check the file `src/lxc/seccomp.c`? It needs porting too.
And also you may want to add `loongarch64` to the list of architectures in the `README.md`.

**Comment by stgraber** [comment]
Marked as Incomplete per above.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@brauner @mihalicyn should be ready to review

**Comment by brauner** [comment]
This fails the arm64 test suites.

**Comment by zhaixiaojuan** [comment]
> This fails the arm64 test suites.

I cannot reproduce this problem locally. This problem seems to have nothing to do with the submitted code.

**Comment by zhaixiaojuan** [comment]
@stgraber 
Hi stgraber,
I checked the error log information(https://jenkins.linuxcontainers.org/job/lxc-github-pull-test/4813/arch=arm64,async=epoll,compiler=gcc,restrict=vm/consoleFull): lxc-test-cloneconfig and lxc-test-unpriv tests failed:     
<pre>
FAIL: lxc-tests: lxc-test-cloneconfig (1s)
---
lxc-destroy: lxctestb: ../src/lxc/tools/lxc_destroy.c: lxc_destroy_main: 241 Container is not defined
Test 1 starting (/tmp/lxctest-wbc9Jr/1.conf)
lxc-destroy: lxctestb2: ../src/lxc/tools/lxc_destroy.c: lxc_destroy_main: 241 Container is not defined
FAIL
---
</pre>
<pre>
FAIL: lxc-tests: lxc-test-unpriv (3s)
---
Name:           c1
State:          RUNNING
PID:            64649
CPU use:        0.02 seconds
BlkIO use:      0 bytes
Link:           veth1001_W6Yz
 TX bytes:      0 bytes
 RX bytes:      0 bytes
 Total bytes:   0 bytes
Name:           c1
State:          RUNNING
PID:            64713
CPU use:        0.02 seconds
BlkIO use:      0 bytes
Link:           veth1001_dYiF
 TX bytes:      0 bytes
 RX bytes:      0 bytes
 Total bytes:   0 bytes
lxc-copy: c1: ../src/lxc/storage/overlay.c: ovl_mount: 490 No such device - Failed to mount "/home/lxcunpriv/.local/share/lxc/c1/rootfs" on "/usr/lib/aarch64-linux-gnu/lxc/rootfs" with options "upperdir=/home/lxcunpriv/.local/share/lxc/c2/overlay/delta,lowerdir=/home/lxcunpriv/.local/share/lxc/c1/rootfs" 
lxc-copy: c1: ../src/lxc/tools/lxc_copy.c: do_clone: 392 Failed to clone
lxc-create c1 20231221090510.203 INFO     confile - ../src/lxc/confile.c:set_config_idmaps:2273 - Read uid map: type u nsid 0 hostid 910000 range 9999
lxc-create c1 20231221090510.203 INFO     confile - ../src/lxc/confile.c:set_config_idmaps:2273 - Read uid map: type g nsid 0 hostid 910000 range 9999
......
lxc-start c1 20231221090511.838 TRACE    commands - ../src/lxc/commands.c:lxc_cmd_timeout:525 - Connection refused - Command "get_init_pid" failed to connect command socket
lxc-start c1 20231221090511.839 TRACE    commands - ../src/lxc/commands.c:lxc_cmd_timeout:525 - Connection refused - Command "get_state" failed to connect command socket
......
</pre>

I tried to set up a test environment locally and removed the code I modified. I found that the two tests lxc-test-cloneconfig and lxc-test-unpriv also failed when running the test.
So I think this problem may be a public problem, I reopen it here to confirm whether the problem is solved.

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
