### PR TITLE
attach: Fix -c option v2 :-D

### PR DESCRIPTION
**Pull request by blenk92**
I think this one is still required ;-)
Orignal PR: https://github.com/lxc/lxc/pull/3946

### CODE REVIEW

**Comment by brauner** [comment]
@blenk92 are you updating the PR? :)

**Comment by blenk92** [comment]
Hi, sorry for the late reply. Adapted the PR but would still like to test that it really works ;-)

**Comment by blenk92** [comment]
> Hi, sorry for the late reply. Adapted the PR but would still like to test that it really works ;-)

patch works for me, thanks for the hint :-)

**Comment by brauner** [comment]
> > Hi, sorry for the late reply. Adapted the PR but would still like to test that it really works ;-)
> 
> patch works for me, thanks for the hint :-)

Thanks for the patch! :)

**Comment by brauner** [comment]
The sanitizer failure is unrelated and I'll fixed that in another branch!

**Pull request merged**
