### PR TITLE
fixes & config key validation

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
arm64 fails with read-only filesystem; probably some disk error or disk full.

**Comment by brauner** [comment]
@evverx this should get rid of all remaining bugs, I would expect.

**Comment by evverx** [comment]
Thanks!

Looks like it's failing to compile locally:
```
$ ./src/tests/oss-fuzz.sh
...
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../src -fPIC -DPIC -Wvla -std=gnu11 -fms-extensions -fdiagnostics-color -Wcast-align -Wstrict-prototypes -fno-strict-aliasing -fstack-protector-strong --param=ssp-buffer-size=4 -g -fcf-protection -Werror=implicit-function-declaration -Wmissing-include-dirs -Wold-style-definition -Winit-self -Wfloat-equal -Werror=return-type -Werror=incompatible-pointer-types -Wformat=2 -Wshadow -Wendif-labels -Werror=overflow -fdiagnostics-show-option -Werror=shift-count-overflow -Wdate-time -Wnested-externs -fasynchronous-unwind-tables -pipe -fexceptions -Warray-bounds -DLXCROOTFSMOUNT=\"/usr/local/lib/lxc/rootfs\" -DLXCPATH=\"/usr/local/var/lib/lxc\" -DLXC_GLOBAL_CONF=\"/usr/local/etc/lxc/lxc.conf\" -DLXCINITDIR=\"/usr/local/libexec\" -DLIBEXECDIR=\"/usr/local/libexec\" -DLXCTEMPLATEDIR=\"/usr/local/share/lxc/templates\" -DLXCTEMPLATECONFIG=\"/usr/local/share/lxc/config\" -DLOGPATH=\"/usr/local/var/log/lxc\" -DLXC_DEFAULT_CONFIG=\"/usr/local/etc/lxc/default.conf\" -DLXC_USERNIC_DB=\"/run/lxc/nics\" -DLXC_USERNIC_CONF=\"/usr/local/etc/lxc/lxc-usernet\" -DDEFAULT_CGROUP_PATTERN=\"\" -DRUNTIME_PATH=\"/run\" -DSBINDIR=\"/usr/local/sbin\" -DAPPARMOR_CACHE_DIR=\"/usr/local/var/cache/lxc/apparmor\" -I ../../src -I ../../src/lxc -I ../../src/lxc/storage -I ../../src/lxc/cgroups -pthread -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -Wvla -std=gnu11 -fms-extensions -Werror -MT liblxc_la-attach.lo -MD -MP -MF .deps/liblxc_la-attach.Tpo -c attach.c  -fPIC -DPIC -o .libs/liblxc_la-attach.o
In file included from af_unix.c:18:
../../src/config.h:369:9: error: 'thread_local' macro redefined [-Werror,-Wmacro-redefined]
#define thread_local __thread
        ^
/usr/include/threads.h:31:10: note: previous definition is here
# define thread_local _Thread_local
         ^
In file included from attach.c:29:
In file included from ./caps.h:8:
../../src/config.h:369:9: error: 'thread_local' macro redefined [-Werror,-Wmacro-redefined]
#define thread_local __thread
        ^
/usr/include/threads.h:31:10: note: previous definition is here
# define thread_local _Thread_local
         ^
1 error generated.
```
Let me double check.

**Comment by brauner** [comment]
MA

> Thanks!
> 
> Looks like it's failing to compile locally:
> 
> ```
> $ ./src/tests/oss-fuzz.sh
> ...
> libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../src -fPIC -DPIC -Wvla -std=gnu11 -fms-extensions -fdiagnostics-color -Wcast-align -Wstrict-prototypes -fno-strict-aliasing -fstack-protector-strong --param=ssp-buffer-size=4 -g -fcf-protection -Werror=implicit-function-declaration -Wmissing-include-dirs -Wold-style-definition -Winit-self -Wfloat-equal -Werror=return-type -Werror=incompatible-pointer-types -Wformat=2 -Wshadow -Wendif-labels -Werror=overflow -fdiagnostics-show-option -Werror=shift-count-overflow -Wdate-time -Wnested-externs -fasynchronous-unwind-tables -pipe -fexceptions -Warray-bounds -DLXCROOTFSMOUNT=\"/usr/local/lib/lxc/rootfs\" -DLXCPATH=\"/usr/local/var/lib/lxc\" -DLXC_GLOBAL_CONF=\"/usr/local/etc/lxc/lxc.conf\" -DLXCINITDIR=\"/usr/local/libexec\" -DLIBEXECDIR=\"/usr/local/libexec\" -DLXCTEMPLATEDIR=\"/usr/local/share/lxc/templates\" -DLXCTEMPLATECONFIG=\"/usr/local/share/lxc/config\" -DLOGPATH=\"/usr/local/var/log/lxc\" -DLXC_DEFAULT_CONFIG=\"/usr/local/etc/lxc/default.conf\" -DLXC_USERNIC_DB=\"/run/lxc/nics\" -DLXC_USERNIC_CONF=\"/usr/local/etc/lxc/lxc-usernet\" -DDEFAULT_CGROUP_PATTERN=\"\" -DRUNTIME_PATH=\"/run\" -DSBINDIR=\"/usr/local/sbin\" -DAPPARMOR_CACHE_DIR=\"/usr/local/var/cache/lxc/apparmor\" -I ../../src -I ../../src/lxc -I ../../src/lxc/storage -I ../../src/lxc/cgroups -pthread -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -Wvla -std=gnu11 -fms-extensions -Werror -MT liblxc_la-attach.lo -MD -MP -MF .deps/liblxc_la-attach.Tpo -c attach.c  -fPIC -DPIC -o .libs/liblxc_la-attach.o
> In file included from af_unix.c:18:
> ../../src/config.h:369:9: error: 'thread_local' macro redefined [-Werror,-Wmacro-redefined]
> #define thread_local __thread
>         ^
> /usr/include/threads.h:31:10: note: previous definition is here
> # define thread_local _Thread_local
>          ^
> In file included from attach.c:29:
> In file included from ./caps.h:8:
> ../../src/config.h:369:9: error: 'thread_local' macro redefined [-Werror,-Wmacro-redefined]
> #define thread_local __thread
>         ^
> /usr/include/threads.h:31:10: note: previous definition is here
> # define thread_local _Thread_local
>          ^
> 1 error generated.
> ```
> 
> Let me double check.

Fixing.

**Pull request merged**
