### PR TITLE
build: add more options for customizing install

### PR DESCRIPTION
**Pull request by adamcstephens**
Trying to get the nix lxc package up to 5.x and these options are helpful to avoid writing to places outside the nix sandbox. The default behavior should be unchanged.

### CODE REVIEW

**Comment by stgraber** [comment]
I'd need to do some tests to be sure, but I thought we couldn't do conditional subdir statements because that also had the side effect of not including things in the dist tarball.

**Comment by stgraber** [comment]
(That's unless you pass all the right flags to cover every feature and so get everything in the dist tarball, but that kinda defeats the point as that target should be as reproducible as possible)

**Comment by adamcstephens** [comment]
I’m open to adjusting if needed. I figured setting them to default enable should be sufficient but I’ll admit I don’t know meson very well. This won’t block the upgrade for us, but I do prefer to upstream instead of carrying patches if possible.

**Comment by adamcstephens** [comment]
@stgraber Do you think this will get consideration, or should I plant to just maintain our own patch to enable building in nixpkgs?

**Comment by stgraber** [comment]
It's been on my to-do to do a proper review for a little while. We should be able to accommodate Nix.

**Comment by adamcstephens** [comment]
Thanks! No rush, I was just auditing my open PRs and figured it'd been long enough to check back in.

**Comment by mihalicyn** [comment]
jenkins: ok to test

**Comment by mihalicyn** [comment]
Looks safe and this does not change default behavior.

LGTM!

**Review by mihalicyn — APPROVED** [review]

**Comment by stgraber** [comment]
Just did a quick diff of before/after tarballs to make sure this isn't causing a bunch of files to be missed and it looks fine:
```
stgraber@dakara:~/data/code/lxc/lxc/a (install-options)$ diff -Nrup orig new | diffstat
 meson.build       |   79 +++++++++++++++++++++++++++++++++++++++++++++----------------------------------
 meson_options.txt |    8 ++++++++
 2 files changed, 53 insertions(+), 34 deletions(-)
```

**Comment by stgraber** [comment]
And also confirmed that our current dist tarball matches the git tree (as in, we're not missing any files outside of this change).

**Pull request merged**
