### PR TITLE
Checkpatch

### PR DESCRIPTION
**Pull request by tcharding**
@brauner commented on another PR that `src/lxc/cmd/lxc_usernsexec.c` could do with some cleaning up.  I parsed `src/lxc/cmd/*.c` with the kernel 'linter' `scripts/checkpatch.pl`.  Here are just fixes to the most obvious ERROR messages.  Just doing a few patches in this PR to see that I'm following protocol.

Code builds but is untested.  I see you guys have CI on your side, are there tests I should be running locally before raising pull requests?

thanks,
Tobin.

Signed-off-by: Tobin C. Harding <me@tobin.cc>

### CODE REVIEW

**Comment by brauner** [comment]
Yep, that sounds good. Yeah, we follow kernel coding style. I once thought about vendoring `checkpatch.pl` in the `LXC` tree.

**Comment by tcharding** [comment]
Man you do **not** want that script in your tree, it is a monster :)

**Comment by brauner** [comment]
> Man you do **not** want that script in your tree, it is a monster :)

Heh. :) We should still point to it in the `CODING_STYLE.md` doc though. Just mention that it should be used to check for obvious style errors.

**Comment by brauner** [comment]
Thanks!

**Pull request merged**
