### PR TITLE
Add a slackware template.

### PR DESCRIPTION
**Pull request by Ponce**
Requires pkgtools and slackpkg (from the slackware-current tree).

Signed-off-by: Matteo Bernardini <ponce@slackbuilds.org>

### CODE REVIEW

**Comment by Ponce** [comment]
this is the same as the previous pull request (#660), only yhe committer name changes.

**Comment by hallyn** [comment]
Hi,

will a new version of this be coming?

**Comment by Ponce** [comment]
sorry for having not noted it here: it has been merged with pull request #666

**Comment by hallyn** [comment]
Awesome, thanks.

**Pull request closed without merging**
