### PR TITLE
lxc: add lpthread to lxc.pc

### PR DESCRIPTION
**Pull request by brauner**
Fixes: #3853
Suggested-by: Tycho Andersen <tycho@tycho.pizza>
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
//Cc @tych0

**Comment by tych0** [comment]
Any chance you want to add ldl too? :)

**Comment by tych0** [comment]
Anyway, this lgtm, thanks!

**Comment by brauner** [comment]
> Any chance you want to add ldl too? :)



> Any chance you want to add ldl too? :)

I added that now. :)

**Comment by tych0** [comment]
Ugh, I think I spoke too soon. seems like libselinux also wants -lpthread and doesn't ask for it, so I think to really fix linking things have to go after Libs.private:

```
atom-lab-5:~/forkhang make lxc
cc   -static  lxc.c  -L/usr/local/lib -llxc -lutil -lpthread -ldl -lcap -lseccomp -lssl -lcrypto -lselinux -o lxc
/usr/bin/ld: /usr/local/lib/liblxc.a(liblxc_la-conf.o): in function `getgname':
/home/tycho/lxc/src/lxc/conf.c:5552: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/local/lib/liblxc.a(liblxc_la-attach.o): in function `lxc_attach_run_shell':
/home/tycho/lxc/src/lxc/attach.c:1832: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(b_addr.o): in function `BIO_lookup_ex':
(.text+0xd12): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(b_sock.o): in function `BIO_gethostbyname':
(.text+0x75): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/libgcc_eh.a(unwind-dw2.o): in function `uw_init_context_1':
(.text+0x1ec5): undefined reference to `pthread_once'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libselinux.a(procattr.o): in function `init_procattr.part.0':
(.text+0x1a3): undefined reference to `pthread_key_create'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libselinux.a(procattr.o): in function `init_procattr':
(.text+0x1c7): undefined reference to `pthread_key_create'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libselinux.a(procattr.o): in function `getprocattrcon_raw':
(.text+0x1fa): undefined reference to `pthread_once'
/usr/bin/ld: (.text+0x214): undefined reference to `pthread_once'
/usr/bin/ld: (.text+0x226): undefined reference to `pthread_setspecific'
/usr/bin/ld: (.text+0x239): undefined reference to `pthread_setspecific'
/usr/bin/ld: (.text+0x309): undefined reference to `pthread_key_create'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libselinux.a(procattr.o): in function `setprocattrcon_raw.constprop.0':
(.text+0x493): undefined reference to `pthread_once'
/usr/bin/ld: (.text+0x4b7): undefined reference to `pthread_once'
/usr/bin/ld: (.text+0x4c9): undefined reference to `pthread_setspecific'
/usr/bin/ld: (.text+0x4dc): undefined reference to `pthread_setspecific'
/usr/bin/ld: (.text+0x51d): undefined reference to `pthread_key_create'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libselinux.a(procattr.o): in function `procattr_destructor':
(.text.exit+0x11): undefined reference to `pthread_key_delete'
/usr/bin/ld: (.text.exit+0x1f): undefined reference to `pthread_key_delete'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libselinux.a(setrans_client.o): in function `init_context_translations':
(.text+0x1ce): undefined reference to `pthread_key_create'
/usr/bin/ld: (.text+0x1ee): undefined reference to `pthread_key_create'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libselinux.a(setrans_client.o): in function `selinux_trans_to_raw_context':
(.text+0x4cd): undefined reference to `pthread_once'
/usr/bin/ld: (.text+0x4ea): undefined reference to `pthread_once'
/usr/bin/ld: (.text+0x509): undefined reference to `pthread_setspecific'
/usr/bin/ld: (.text+0x51c): undefined reference to `pthread_setspecific'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libselinux.a(setrans_client.o): in function `selinux_raw_to_trans_context':
(.text+0x71d): undefined reference to `pthread_once'
/usr/bin/ld: (.text+0x73a): undefined reference to `pthread_once'
/usr/bin/ld: (.text+0x759): undefined reference to `pthread_setspecific'
/usr/bin/ld: (.text+0x76c): undefined reference to `pthread_setspecific'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libselinux.a(setrans_client.o): in function `selinux_raw_context_to_color':
(.text+0x96f): undefined reference to `pthread_once'
/usr/bin/ld: (.text+0x98c): undefined reference to `pthread_once'
/usr/bin/ld: (.text+0xa6b): undefined reference to `pthread_setspecific'
/usr/bin/ld: (.text+0xa7e): undefined reference to `pthread_setspecific'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libselinux.a(setrans_client.o): in function `setrans_lib_destructor':
(.text.exit+0x19): undefined reference to `pthread_key_delete'
/usr/bin/ld: (.text.exit+0x27): undefined reference to `pthread_key_delete'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): in function `CRYPTO_THREAD_lock_new':
(.text+0x4a): undefined reference to `pthread_rwlock_init'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): in function `CRYPTO_THREAD_read_lock':
(.text+0x89): undefined reference to `pthread_rwlock_rdlock'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): in function `CRYPTO_THREAD_write_lock':
(.text+0xa9): undefined reference to `pthread_rwlock_wrlock'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): in function `CRYPTO_THREAD_unlock':
(.text+0xc9): undefined reference to `pthread_rwlock_unlock'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): in function `CRYPTO_THREAD_lock_free':
(.text+0xee): undefined reference to `pthread_rwlock_destroy'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): in function `CRYPTO_THREAD_run_once':
(.text+0x129): undefined reference to `pthread_once'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): in function `CRYPTO_THREAD_init_local':
(.text+0x149): undefined reference to `pthread_key_create'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): in function `CRYPTO_THREAD_set_local':
(.text+0x17b): undefined reference to `pthread_setspecific'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): in function `CRYPTO_THREAD_cleanup_local':
(.text+0x19b): undefined reference to `pthread_key_delete'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): in function `openssl_init_fork_handlers':
(.text+0x207): undefined reference to `pthread_once'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): in function `CRYPTO_THREAD_get_local':
(.text+0x167): undefined reference to `pthread_getspecific'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): in function `dlfcn_globallookup':
(.text+0x17): undefined reference to `dlopen'
/usr/bin/ld: (.text+0x2a): undefined reference to `dlsym'
/usr/bin/ld: (.text+0x35): undefined reference to `dlclose'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): in function `dlfcn_pathbyaddr':
(.text+0x86): undefined reference to `dladdr'
/usr/bin/ld: (.text+0xf7): undefined reference to `dlerror'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): in function `dlfcn_bind_func':
(.text+0x407): undefined reference to `dlsym'
/usr/bin/ld: (.text+0x4d2): undefined reference to `dlerror'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): in function `dlfcn_load':
(.text+0x545): undefined reference to `dlopen'
/usr/bin/ld: (.text+0x5b9): undefined reference to `dlclose'
/usr/bin/ld: (.text+0x5f5): undefined reference to `dlerror'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): in function `dlfcn_unload':
(.text+0x6b8): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
make: *** [<builtin>: lxc] Error 1
atom-lab-5:~/forkhang 2 cat Makefile 
export LDFLAGS=-static
# export LDLIBS=$(shell pkg-config --libs --static lxc) -lpthread -ldl
export LDLIBS=$(shell pkg-config --libs --static lxc)

clean:
	-rm lxc standalone
atom-lab-5:~/forkhang 127 pkg-config --libs --static lxc
-L/usr/local/lib -llxc -lutil -lpthread -ldl -lcap -lseccomp -lssl -lcrypto -lselinux
```

**Pull request merged**
