### PR TITLE
commands: fix wrong function used by get_cgroup

### PR DESCRIPTION
**Pull request by lifeng68**
Signed-off-by: lifeng68 <lifeng68@huawei.com>

### CODE REVIEW

**Comment by brauner** [comment]
Oh, it seems you made this fix against stable-4.0. Can you make the pr against master, please? I'll just backport it to stable-4.0 right after merging it.

**Comment by lifeng68** [comment]
@brauner I found this issue in release lxc-4.0.3, and i found this issue had beed fixed on master, but exist on stable-4.0 branch. So i make this PR.

**Comment by brauner** [comment]
Hm, that's odd. Let me look at this a little closer now that OSS NA is over.

**Comment by brauner** [comment]
Sorry, apparently we forgot to backport this. I've backported the original fix that @Blub did now. :)
https://github.com/lxc/lxc/commit/3a7f78f9203ab7b01211419476eb469fdacfeb9e

**Pull request closed without merging**
