### PR TITLE
seccomp: fixes

### PR DESCRIPTION
**Pull request by brauner**
Suggested-by: Jann Horn <jann@thejh.net>
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
//cc @thejh the code is in `src/lxc/seccomp.c`

**Comment by brauner** [comment]
I'm sure there's bugs lurking!

**Comment by brauner** [comment]
I think you want to look at `seccomp_notify_handler`.

**Comment by thejh** [comment]
uuuugh... so libseccomp was actually exposing this stuff already?

**Comment by brauner** [comment]
> uuuugh... so libseccomp was actually exposing this stuff already?

It is, yes! There ware quite a few bugs too!

**Comment by thejh** [comment]
funny, when you search debian codesearch for "seccomp_notify_receive", it doesn't find the definition in libseccomp, only the use in LXC

**Comment by brauner** [comment]
https://github.com/seccomp/libseccomp/pull/280
That was the last bug.

**Pull request merged**
