### PR TITLE
include: simplify strlcpy()

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by 2xsec** [comment]
@brauner I think all issues are related strlcpy() will be fixed with this patch. Actually, other cases are fixed in our side.

**Comment by 2xsec** [comment]
==lxc-attach==3249==ERROR: AddressSanitizer: global-buffer-overflow on address 0x00014f68 at pc 0xb613fa11 bp 0xbe3bf380 sp 0xbe3bf384
READ of size 4 at 0x00014f68 thread T0
    #0 0xb613fa0f in strlcpy
    #1 0xb60c7013 in lxc_log_init
    #2 0x117ff in main
    #3 0xb5eb3867 in __libc_start_main

**Comment by 2xsec** [comment]
==zone-launcher==1030==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xb4560758 at pc 0xb60a7899 bp 0xbe16e390 sp 0xbe16e394
READ of size 4 at 0xb4560758 thread T0
    #0 0xb60a7897 in strlcpy
    #1 0xb605f94f in lxc_monitor_send_state
    #2 0xb6068e6d in lxc_set_state
    #3 0xb606a1b7 in lxc_init
    #4 0xb60700af in __lxc_start
    #5 0xb6070cc9 in lxc_start
    #6 0xb6042577 in do_lxcapi_start
    #7 0xb604351d in lxcapi_start
    #8 0x4d1b31 in main
    #9 0xb5cdc867 in __libc_start_main

**Comment by 2xsec** [comment]
@brauner Thanks. :)

**Comment by brauner** [comment]
Oh no worries, I'm guilty of using a complicated version of `strlcpy()`. Keeping it simple is usually better. :)

**Pull request merged**
