### PR TITLE
Use %m instead of strerror() when available

### PR DESCRIPTION
**Pull request by Rachid-Koucha**
Use %m under HAVE_M_FORMAT instead of strerror()

Signed-off-by: Rachid Koucha <rachid.koucha@gmail.com>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Does `%m` use a thread-safe way of getting at the `errno`?

**Comment by Rachid-Koucha** [comment]
> Does `%m` use a thread-safe way of getting at the `errno`?

This is a good question !

It is done inside GLIBC. I guess it hides a call to strerror() internally. The Linux manual of printf() merely says the following :

m      (Glibc extension; supported by uClibc and musl.)  Print output of strerror(errno).  No argument is required.

And strerror() source code is not thread-safe as it uses a static global malloced internal buffer into which it stores the error string. Here is the source code of strerror in GLIBC 2.29:

/* Return a string describing the errno code in ERRNUM.
   The storage is good only until the next call to strerror.
   Writing to the storage causes undefined behavior.  */
libc_freeres_ptr (static char *buf);

char *
strerror (int errnum)
{
  char *ret = __strerror_r (errnum, NULL, 0);
  int saved_errno;

  if (__glibc_likely (ret != NULL))
    return ret;
  saved_errno = errno;
  if (buf == NULL)
    buf = malloc (1024);
  __set_errno (saved_errno);
  if (buf == NULL)
    return _("Unknown error");
  return __strerror_r (errnum, buf, 1024);
}

So, I would say no : %m is not thread safe :-(

**Comment by Rachid-Koucha** [comment]
There is also a discussion here saying that %m would be thread-safe. So, I am confused...

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=621057

**Comment by Rachid-Koucha** [comment]
I dived into the source code og GLIBC/printf(). And it appears that '%m' is thread-safe as it hides a call to strerror_r() to write into the user buffer (in case of snprintf() or the the internal buffer of GLIBC in case of printf(). Here is the source code (from GLIBC2.29/stdio-common/vfprintf-internal.c):

    LABEL (form_strerror):						      \
      /* Print description of error ERRNO.  */				      \
      string =								      \
	(CHAR_T *) __strerror_r (save_errno, (char *) work_buffer,	      \
				 WORK_BUFFER_SIZE * sizeof (CHAR_T));	      \
      is_long = 0;		/* This is no wide-char string.  */	      \
      goto LABEL (print_string)

So, I would say that %m is thread-safe.

**Pull request merged**
