### PR TITLE
conf: fix chroot jail issue

### PR DESCRIPTION
**Pull request by 2xsec**
Hello,

chroot jail issue is fixed.

Thanks.

Signed-off-by: 2xsec <dh48.jeong@samsung.com>

### CODE REVIEW

**Comment by 2xsec** [comment]
@brauner It is possible to access file system outside of the chroot directory if the current directory is not contained in it. It is just possibility related security issue. But, we also need your opinion. Please review it. :)

**Comment by Blub** [comment]
But we use `chroot(".")`, iow, chroot into "the current directory". Is it still possible for `/` not to be the same as `./` in this case?

**Comment by 2xsec** [comment]
@Blub Do you know why a working directory of this is changed to new root by this code?

	/* It is weird, but chdir("..") moves us in a new root */
	ret = chdir("..");
	if (ret < 0) {
		SYSERROR("Failed to chdir(\"..\")");
		return -1;
	}

**Comment by brauner** [comment]
Ok :)

**Pull request closed without merging**
