### PR TITLE
Fix attach c

### PR DESCRIPTION
**Pull request by blenk92**
Currently, the -c command (to set the selinux context) seems to be
broken because lxc-attach expects that also a new mount namespace
is specified via command line. This commit remove the check for the new
mount namespace to fix this issue. Please note that the
--elevated-privileges option is not affected by this issue.

Current situation:
```
~ # lxc-attach -n container --elevated-privileges=LSM
~ # id
uid=0(root) gid=0(root) context=u:r:unconfined_t:s0
# can not enter container
~ # lxc-attach -n container -c u:r:unconfined_t:s0
lxc-attach: node1: attach.c: lxc_attach_run_shell: 1860 Permission denied - Failed to execute shell
```

Expected:
```
~ # lxc-attach -n container --elevated-privileges=LSM
~ # id
uid=0(root) gid=0(root) context=u:r:unconfined_t:s0
# works
~ # lxc-attach -n container -c u:r:unconfined_t:s0
# in container now
~ # id
uid=0(root) gid=0(root) context=u:r:unconfined_t:s0
```

Please also note that when --elevated-privileges=LSM and -c are specified the -c context is silently ignored. This was pretty confusing to me since `-c u:r:unconfined_t:s0` didn't work (due to the bug) but `-c u:r:init_t:s0 -e` did work but transited into the `unconfined_t` context. Thus, i've added a patch to make the -c and the lsm privileges option exclusive.

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by blenk92** [comment]
Hi @brauner saw you spend some effort to create the other PR. Unfortunately i got tricked by another issue in our system (labeling wasn't working properly so i accidentally ended up in the desired context without violations). I spend some more time debugging whats going on and i think i found the root cause now: The context passed via the -c is completely ignored and always the context specified in the config file is taken. This patch should fix the issue by just overwriting the context parsed from the config file if a context has been passed via command line

**Comment by brauner** [comment]
> Hi @brauner saw you spend some effort to create the other PR. Unfortunately i got tricked by another issue in our system (labeling wasn't working properly so i accidentally ended up in the desired context without violations). I spend some more time debugging whats going on and i think i found the root cause now: The context passed via the -c is completely ignored and always the context specified in the config file is taken. This patch should fix the issue by just overwriting the context parsed from the config file if a context has been passed via command line. Sorry for the confusion...

Ah. Should we still merge the other branch  I sent and you sent a separate PR on top of that?

**Comment by brauner** [comment]
Closing this PR as we've merged your patches and a few additional ones in another PR. Please do send a PR in case there's anything to fix still!

**Pull request closed without merging**
