### PR TITLE
compiler: compiler based hardening

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by Blub** [comment]
I always wondered why the members of `struct ifaddrs` are defined as `struct sockaddr*` and not `struct sockaddr_storage*` (which AFAIK is supposed to be able to contain all variants of it and should prevent this kind of warning here).
Is this the point where we start using `#pragma clang diagnostic push`+`...ignored "-Wcast-align"`+`... pop` sections? Since with the af_family checks these casts are legal after all.

**Comment by brauner** [comment]
> I always wondered why the members of struct ifaddrs are defined as struct sockaddr* and not struct sockaddr_storage* (which AFAIK is supposed to be able to contain all variants of it and should prevent this kind of warning here).
Is this the point where we start using #pragma clang diagnostic push+...ignored "-Wcast-align"+... pop sections? Since with the af_family checks these casts are legal after all.

The short and generic answer is: anything that hardens the codebase is good. So anything that you want in that direction will be received with generous support. :)
The only things I would like to add:
- The hardening must be reasonable wrt to performance. An example is `fstack-protector-all` probably too much and has performance impact better use `fstack-protector-strong` since it has a lot of benefit but does not impact peformance.
- The hardening must defend against something that is a plausible attach on the library. For example, we likely don't need encryption-based hardening options since we don't do encryption.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@brauner try rebasing on master + force-push that may fix it

**Comment by brauner** [comment]
yup, will do

**Pull request merged**
